<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BUOL TOLI-TOLI - JL. SYARIF MANSYUR (JL_d4d948</name>
   <tag></tag>
   <elementGuidId>ce68be2d-f70c-432b-9f83-57abdf6add70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#react-select-2-option-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e20fbec1-f8a2-46b3-be06-fbc503dbd636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1czt1k7-option</value>
      <webElementGuid>a26e2271-d0af-4c94-84b8-5adb1decd658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0989297-9007-4337-a570-a78b6dd28d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-1</value>
      <webElementGuid>c7a519e3-988b-498d-a8c8-4cebbaeb2aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c7e2a17e-558c-4613-be71-bce0ca7adcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>22d18259-1545-4295-b1e9-252cd475725e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24e07134-d356-4d80-b634-6b511cbc11ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUOL TOLI-TOLI - JL. SYARIF MANSYUR (JL.RAYA BUOL, KAB.BUOUL) TOLI-TOLI</value>
      <webElementGuid>a4fe99cf-77ec-4f6f-93d1-3b934ce6faad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-1&quot;)</value>
      <webElementGuid>5348d90b-f831-4576-8f81-73d062110a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-1']</value>
      <webElementGuid>49540156-419f-4b61-8c30-99dce4abd35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div[2]</value>
      <webElementGuid>ccc75a81-fa55-4404-b450-123ae11e3abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAHUNA - JL. MALAHASA NO. 1 - TAHUNA'])[1]/following::div[1]</value>
      <webElementGuid>ad496e09-5c74-4257-b498-99d7bf321d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih cabang tujuan'])[1]/following::div[7]</value>
      <webElementGuid>84bbb91d-07f9-42ee-92c7-54e49f2f4fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAROPEN - JL. INPRES NO. 17, UREI FASAI (URFAS), WAREN, KAB. WAROPEN'])[1]/preceding::div[1]</value>
      <webElementGuid>fc43282b-9c14-457e-ba9e-0d1b1a542696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTROP - JL. RAYA KELAPA II ENTROP, KOTA JAYAPURA'])[1]/preceding::div[2]</value>
      <webElementGuid>ec6e61f8-7c0a-4c92-a313-07bf8e626bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BUOL TOLI-TOLI - JL. SYARIF MANSYUR (JL.RAYA BUOL, KAB.BUOUL) TOLI-TOLI']/parent::*</value>
      <webElementGuid>22f3d0ec-5569-411d-90dc-1a9293c8dc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]</value>
      <webElementGuid>d9e9c47d-b9f8-450b-95ed-f9d6b3da0d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-1' and (text() = 'BUOL TOLI-TOLI - JL. SYARIF MANSYUR (JL.RAYA BUOL, KAB.BUOUL) TOLI-TOLI' or . = 'BUOL TOLI-TOLI - JL. SYARIF MANSYUR (JL.RAYA BUOL, KAB.BUOUL) TOLI-TOLI')]</value>
      <webElementGuid>c88ccb34-70a9-4015-b8c6-0f126e2dff2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
