<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Klik untuk upload atau drag and dropFor_c29bdb</name>
   <tag></tag>
   <elementGuidId>c63e23f2-1d63-4cfe-98ba-39270d3e9db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[18]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-dvxtzn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG \(max\. 500kb\)$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55ae1132-8264-4b72-adce-7b3b9cba441e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-dvxtzn</value>
      <webElementGuid>18d2b902-05e8-423e-86b9-0852e181217e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG (max. 500kb)</value>
      <webElementGuid>3521b39a-dd77-48c1-9963-3d0f36e9e898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-1gtf5cl&quot;]/label[18]/div[@class=&quot;css-1n9kzij&quot;]/div[@class=&quot;css-dvxtzn&quot;]</value>
      <webElementGuid>7f5d6703-a2f3-4687-b768-e2c9533c6713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[18]/div/div</value>
      <webElementGuid>2bdc63e1-d56f-4797-92b2-079f0b880e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[2]</value>
      <webElementGuid>4ea843b8-ca67-4c20-9d78-9711b555c005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[18]/div/div</value>
      <webElementGuid>cc424da1-db05-47db-a786-320559171e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG (max. 500kb)' or . = 'Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG (max. 500kb)')]</value>
      <webElementGuid>c866d439-a19f-45e6-b4c2-8100561e28f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
