<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Klik untuk upload atau drag and dropF_848054</name>
   <tag></tag>
   <elementGuidId>77976f7c-f3a9-44f0-92a4-6ddd57dea192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label:nth-of-type(12)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label:nth-child(13)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a521cd1a-e1b2-4e76-9917-646942d32ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>fileInput-AktaPerubahan</value>
      <webElementGuid>59ec994d-be4f-408b-a356-91cb521844d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Klik untuk upload atau drag and dropFormat PDF [max. 1Mb]</value>
      <webElementGuid>ff36ef1c-5194-44c9-943a-e8cc2d7ac4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-1gtf5cl&quot;]/label[12]</value>
      <webElementGuid>196a9cb6-e616-402f-8e7c-430a6f56f4f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[12]</value>
      <webElementGuid>9da9d11d-0ce5-4e77-9e04-f4243ca5a38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akta Perubahan Terakhir'])[1]/following::label[1]</value>
      <webElementGuid>a7c076e1-fd0c-41e7-afbb-dec853913086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[12]</value>
      <webElementGuid>30417e08-a56c-49a6-937c-8be6adfec850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Klik untuk upload atau drag and dropFormat PDF [max. 1Mb]' or . = 'Klik untuk upload atau drag and dropFormat PDF [max. 1Mb]')]</value>
      <webElementGuid>047dc894-7feb-4df1-8a73-aa5296238e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
