<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Kelolaan Dana Pertahun Rp100 j_ced9d8</name>
   <tag></tag>
   <elementGuidId>49f2d2dc-aa62-4ca4-acc3-e2ec156f6250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='onboardDto.annualFundMgmt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Kelolaan Dana Pertahun*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9e391fb5-5920-4a49-bd01-84e89718266b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.annualFundMgmt</value>
      <webElementGuid>4bcf1354-4891-46f7-a241-05f9681cfcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.annualFundMgmt</value>
      <webElementGuid>7e95eee6-8ab5-4292-adf9-2a2f7059f84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a7b6bc5-6cd6-4fa7-ac9d-3d2bb92d4089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>15e9bcfb-32b7-4d2f-aa68-5c169874fd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kelolaan Dana Pertahun&lt;= Rp100 jt&lt;= Rp100 jt - Rp300 jt&lt;= Rp300 jt - Rp2.5 M&lt;= Rp50 M - Rp300 M&lt;= Rp300 M - Rp600 M</value>
      <webElementGuid>785311a7-0ca5-4939-b04f-cdf05885b585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.annualFundMgmt&quot;)</value>
      <webElementGuid>f2b58423-29ce-45bc-bea8-5bd8e7cc8f05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardDto.annualFundMgmt']</value>
      <webElementGuid>88b41179-185f-41fc-a820-fad7c9548c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[9]/div/div/select</value>
      <webElementGuid>4b094a6b-92a5-4f75-9c67-44aadc344f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::select[1]</value>
      <webElementGuid>5bf26d5c-442f-4a6b-95a2-9c1ca5ed3f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Pelanggan'])[1]/preceding::select[1]</value>
      <webElementGuid>5495bfa0-204c-4beb-a4fc-427edb894f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/select</value>
      <webElementGuid>f87ffb0a-4112-4e64-a09a-64067821283a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.annualFundMgmt' and @id = 'onboardDto.annualFundMgmt' and (text() = 'Pilih Kelolaan Dana Pertahun&lt;= Rp100 jt&lt;= Rp100 jt - Rp300 jt&lt;= Rp300 jt - Rp2.5 M&lt;= Rp50 M - Rp300 M&lt;= Rp300 M - Rp600 M' or . = 'Pilih Kelolaan Dana Pertahun&lt;= Rp100 jt&lt;= Rp100 jt - Rp300 jt&lt;= Rp300 jt - Rp2.5 M&lt;= Rp50 M - Rp300 M&lt;= Rp300 M - Rp600 M')]</value>
      <webElementGuid>f5000916-4be6-42f9-9f80-fd768fe1579e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
