<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Tujuan Pembukaan RekeningInves_a44001</name>
   <tag></tag>
   <elementGuidId>2b8e3a94-e1fd-4e44-a809-491a85093d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='onboardPermitsDto.openAccountGoal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tujuan Pembukaan Rekening&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>196c1f35-a610-4fa0-adaa-db4d8da82ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardPermitsDto.openAccountGoal</value>
      <webElementGuid>9908a98e-35f7-4c75-af8e-1dd72ad0cb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardPermitsDto.openAccountGoal</value>
      <webElementGuid>1f32336a-ab7b-4afd-8e33-b2b24bda302c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>5364ea14-4667-4a26-b583-3fab00214a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi</value>
      <webElementGuid>7d98a1fb-c2f2-4ee7-b4f1-e7fc043761bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardPermitsDto.openAccountGoal&quot;)</value>
      <webElementGuid>97df72e5-f5ef-4530-821d-85697ae88a8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardPermitsDto.openAccountGoal']</value>
      <webElementGuid>98bef1e4-a2ce-4179-b665-ee3bb5a65d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div[2]/div[4]/div/div/div/div/div/select</value>
      <webElementGuid>f2a6d5a2-2dc1-4600-be28-4b9137afbd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan Pembukaan Rekening'])[1]/following::select[1]</value>
      <webElementGuid>b62e7f22-6c69-4ee3-8853-34724b13dd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Memiliki Giro'])[1]/following::select[1]</value>
      <webElementGuid>d0f95a85-354f-4ebd-9455-3fd6732a72a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro Rupiah'])[1]/preceding::select[1]</value>
      <webElementGuid>79afcb56-c925-4712-a03a-b90222357304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro Valas'])[1]/preceding::select[1]</value>
      <webElementGuid>86a2386f-0665-4b19-9af1-c5249e837b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4064f80c-7b94-4d38-a601-d4b78f679622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardPermitsDto.openAccountGoal' and @id = 'onboardPermitsDto.openAccountGoal' and (text() = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi' or . = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi')]</value>
      <webElementGuid>d7bf9689-638b-413b-80e9-acbc50169540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
