<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KotaKepulauan SeribuJakarta Pu_905aab</name>
   <tag></tag>
   <elementGuidId>c022dea7-ec48-4d63-9b4a-b93a673aa1da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='field-:ri:'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;onboardDto\.cityId&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae5ff97d-bfff-492a-88f4-569919e0a95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.cityId</value>
      <webElementGuid>8e0ff9fe-cd68-4c92-9104-f15fac18c842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:ri:</value>
      <webElementGuid>1033efa5-6c4c-4ab2-a640-e17d6ee87ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-l1m0k1</value>
      <webElementGuid>baadc938-91ac-4159-b800-69903f3f6ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KotaKepulauan SeribuJakarta PusatJakarta BaratJakarta TimurJakarta SelatanJakarta Utara</value>
      <webElementGuid>3eab2b58-4c06-4c26-81f7-0a79f941457c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-16djiq0&quot;]/form[1]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-select__wrapper css-15ca0qf&quot;]/select[@id=&quot;field-:ri:&quot;]</value>
      <webElementGuid>0982deb4-df21-442f-acd7-c32d98621d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='field-:ri:'])[3]</value>
      <webElementGuid>c1cda58e-7935-4bad-bbe9-5199f8cd002e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[3]/div[3]/div/select</value>
      <webElementGuid>5ba71e1c-3083-424f-bdfb-6aa7d024df21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>1059dd68-6424-4c41-b2e5-9a1e10cc1599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>bd238286-264d-4861-b992-e1984154644f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>ed303965-b408-4b86-a780-022db9163f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.cityId' and @id = 'field-:ri:' and (text() = 'Pilih KotaKepulauan SeribuJakarta PusatJakarta BaratJakarta TimurJakarta SelatanJakarta Utara' or . = 'Pilih KotaKepulauan SeribuJakarta PusatJakarta BaratJakarta TimurJakarta SelatanJakarta Utara')]</value>
      <webElementGuid>4ef836a5-1ebf-41db-a66f-5935aa9f6c0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
