<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Bentuk Badan UsahaPTBankKopera_6d3d37</name>
   <tag></tag>
   <elementGuidId>2dae5ebf-391f-4b8d-8743-d71bbe066d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='onboardDto.compEntityTypeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bentuk Badan Usaha*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cc2c1706-f117-4826-86e2-17856aa74e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compEntityTypeId</value>
      <webElementGuid>e3f232e5-ae49-4bdd-b674-961f6dcf4ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compEntityTypeId</value>
      <webElementGuid>fad83c93-930f-4367-854b-62d81b0ce4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>abb465b3-ad98-4b30-ab23-7776cdd59196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>2ad5b133-9606-4bdd-a5f5-7b49e5bc0da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA</value>
      <webElementGuid>3def0ff8-8ab9-459d-bc80-76dc9ffdb1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.compEntityTypeId&quot;)</value>
      <webElementGuid>f974b7af-1c40-416b-941d-c6b07fac926e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardDto.compEntityTypeId']</value>
      <webElementGuid>91d03013-34e4-4348-ab62-70dde5bf593f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>2f076452-dccf-4b42-9eae-272110b7fe26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/following::select[1]</value>
      <webElementGuid>350513dd-41a0-41e1-aa79-e0bb8e4ac16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ec876ef3-3724-4072-b46a-d16358cceb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.compEntityTypeId' and @id = 'onboardDto.compEntityTypeId' and (text() = 'Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA' or . = 'Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA')]</value>
      <webElementGuid>f29125cd-101c-408f-96d7-2dc27e67f5fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
