<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jl. Kemanggis</name>
   <tag></tag>
   <elementGuidId>105bccbf-992f-4585-96d2-60b0cf71fe80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='onboardDto.compAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Alamat Lengkap&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6cd9ca50-767c-4926-8afd-e7e1a3c66a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>0f5c0f10-3985-42d8-9fa1-24127175c231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Lengkap</value>
      <webElementGuid>046d6a67-5a56-4b3f-a13d-574f94a485c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>2114ea4c-7226-4521-a11c-bfc842e45534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5c34073b-fce4-4d56-9d0e-4c8f0ca6bfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-textarea w-full bg-white border border-gray-300 hover:border-[#FF6B00] px-4 py-2 text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-31809p</value>
      <webElementGuid>2652c281-e7e1-42a9-b5a3-e79765a71f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Kemanggis</value>
      <webElementGuid>16178bb4-d536-47d6-8c39-a8790e064cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.compAddress&quot;)</value>
      <webElementGuid>795732c1-6b86-4138-b1a1-051a9dbe7ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='onboardDto.compAddress']</value>
      <webElementGuid>e88659f6-bb20-417f-89a3-ba3d61faecce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[4]/textarea</value>
      <webElementGuid>e8339af9-09c9-40eb-8b39-8ad8b5bb7acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Email Perusahaan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>26e89b09-5ee5-4d31-8526-93f0176d332b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jl. Kemanggis']/parent::*</value>
      <webElementGuid>1ab21f97-7351-4d1e-a9f1-c8db12e5fef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3e1eeb81-2ab6-41bb-874d-aa42213baf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'onboardDto.compAddress' and @placeholder = 'Masukkan Alamat Lengkap' and @id = 'onboardDto.compAddress' and (text() = 'Jl. Kemanggis' or . = 'Jl. Kemanggis')]</value>
      <webElementGuid>e5455317-2275-4741-ab30-7aaf24dec578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
