<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jl. Kemanggisan Ilir_1</name>
   <tag></tag>
   <elementGuidId>633b7b0c-1d6b-4533-a751-3979014ea4ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='onboardDto.compAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Alamat Lengkap&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>11295d65-22cd-4d09-ad11-cbcf75a7d447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>325ed27a-be44-4c2d-a029-020ddd70c969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Lengkap</value>
      <webElementGuid>8d5c5d49-1f0c-4c82-b72d-f18295104911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>8eb51e04-b75f-4692-afbb-775d9d641632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75b168e2-6694-447f-8aec-c949cc92a4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-textarea w-full bg-white border border-gray-300 hover:border-[#FF6B00] px-4 py-2 text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-31809p</value>
      <webElementGuid>29447006-8e94-4ce3-a84e-289b68fba930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Kemanggisan Ilir </value>
      <webElementGuid>eff98a9a-0f17-4369-8a0f-d7a943daf2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.compAddress&quot;)</value>
      <webElementGuid>dd4768e5-1ffc-4ac5-b98d-0c4820517438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='onboardDto.compAddress']</value>
      <webElementGuid>f591c038-ab1b-478e-9493-cfaf4d021b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[4]/textarea</value>
      <webElementGuid>3e31196d-5456-4767-a42b-6531bb3f98dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Email Perusahaan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ed91bef3-9945-4172-b035-9acd6774be64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jl. Kemanggisan Ilir']/parent::*</value>
      <webElementGuid>593f1e55-cf26-4d1e-a6b3-d612fd3ffbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8e5e59f4-eeee-4b78-8cf2-7a36259bd92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'onboardDto.compAddress' and @placeholder = 'Masukkan Alamat Lengkap' and @id = 'onboardDto.compAddress' and (text() = 'Jl. Kemanggisan Ilir ' or . = 'Jl. Kemanggisan Ilir ')]</value>
      <webElementGuid>6c018a69-70bc-48fd-8799-dd4d056b8854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
