<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>_negative_TC_070_NIBMaxDigit</name>
   <tag></tag>
   <elementGuidId>bd1cb81d-b001-4c55-85e0-c9c6dc71b01c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'NIB harus maksimal 13 digit' or . = 'NIB harus maksimal 13 digit')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[13]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c9af809-b0ce-4aa2-877a-81d96f18de5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIB harus maksimal 13 digit</value>
      <webElementGuid>f1c4df8b-ae1a-472e-bdc0-4c1520d14a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[13]/div[2]</value>
      <webElementGuid>f1e2073b-5287-426a-b13c-1d06160b5fb6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
