<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_050_NamaPerusahaanKosong</name>
   <tag></tag>
   <elementGuidId>160357fb-6f46-4868-9b91-5e5daa6b6461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'onboardDto.compName' and @placeholder = 'Masukkan Nama Perusahaan' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc9662ae-868e-43a0-9adc-21da376f2638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compName</value>
      <webElementGuid>971f18a8-29fe-4ce7-a2c5-a4b399a610de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Perusahaan</value>
      <webElementGuid>71a658c8-a0f5-4319-bf7c-6e8a631ab595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f910d4f-65bd-4657-b01a-da0131430656</webElementGuid>
   </webElementProperties>
</WebElementEntity>
