<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_093_cabangHarusdipilih</name>
   <tag></tag>
   <elementGuidId>2c35c3ef-6fd8-4752-9c05-3c1393881d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'react-select-2-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ff67ced-9836-4b35-8027-bb490672f375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-input</value>
      <webElementGuid>2c1543a4-4414-4dd3-8b66-a9b6e5cb1ca7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
