<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_062_KodePosKosong</name>
   <tag></tag>
   <elementGuidId>f2644879-ba98-4c6d-9a6c-9609b415828a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[3]/div[2][count(. | //input[@name = 'onboardDto.postalCode&quot;']) = count(//input[@name = 'onboardDto.postalCode&quot;'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;onboardDto.postalCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.postalCode&quot;</value>
      <webElementGuid>4d292227-a092-46d1-a979-caab3a9eeba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fc882dc-c3b8-4fb1-b466-192ec7ded099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[3]/div[2]</value>
      <webElementGuid>6ff46acd-ba7e-4c42-9547-ddd9a76b4673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Pos</value>
      <webElementGuid>863601a7-ef9f-4add-afda-9e7e4b9b254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d486f75-be92-4b41-9819-60ff1d7d5ec8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
