<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12.8_click_CabangPendaftaran</name>
   <tag></tag>
   <elementGuidId>39787927-99a9-4a64-9fa3-6b03f6e0dc2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[1]/div[18]/div/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9b6acd1-0ddf-4e90-930e-7b53ca6c53d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1b6elut</value>
      <webElementGuid>7aebb73b-5b1f-418d-8c12-d41d388ed734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>System Administration Registration</value>
      <webElementGuid>5d124e1b-fc43-4c5d-ae05-9386f7e6ceb4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
