<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3.2_select_Pilih Tujuan Pembukaan RekeningInves_a44001</name>
   <tag></tag>
   <elementGuidId>32c790c5-1771-431a-8be5-def34aaf701d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'onboardPermitsDto.openAccountGoal' and @id = 'onboardPermitsDto.openAccountGoal' and (text() = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi' or . = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='onboardPermitsDto.openAccountGoal']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tujuan Pembukaan Rekening&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba8da374-19c3-4aa6-afb8-61155b7fee9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardPermitsDto.openAccountGoal</value>
      <webElementGuid>7e4b1d3d-e26c-44eb-86f1-10f628fb00b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardPermitsDto.openAccountGoal</value>
      <webElementGuid>8702964f-c48a-4ea0-a8f6-ad4211ab3232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>92950e47-cc0b-4bbb-8ed7-d8b66c35bf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi</value>
      <webElementGuid>c8a9d818-5d1b-48cc-a2cb-5c187441ace1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardPermitsDto.openAccountGoal&quot;)</value>
      <webElementGuid>0d070dd7-5f3a-4aae-8998-cd35db83af4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Investasi</value>
      <webElementGuid>bc6947b7-d46f-4df0-a614-f397e11c8a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardPermitsDto.openAccountGoal']</value>
      <webElementGuid>6b043bf2-ccb7-41f4-bb62-3899471c9448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div[2]/div[4]/div/div/div/div/div/select</value>
      <webElementGuid>90a48b9f-3017-473f-a679-3972f5a91e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan Pembukaan Rekening'])[1]/following::select[1]</value>
      <webElementGuid>d22a10f2-571f-40f5-ac10-db8961a78f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Memiliki Giro'])[1]/following::select[1]</value>
      <webElementGuid>1a29bf59-a330-4976-aac2-37d8878ebe0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro Rupiah'])[1]/preceding::select[1]</value>
      <webElementGuid>0476f8b1-82c9-4fed-9e45-111dae2698f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro Valas'])[1]/preceding::select[1]</value>
      <webElementGuid>ad04e5b9-304d-4de1-bf00-839f372fdd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b604e9fd-197a-4932-9b9b-1d5216557672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardPermitsDto.openAccountGoal' and @id = 'onboardPermitsDto.openAccountGoal' and (text() = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi' or . = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi')]</value>
      <webElementGuid>cd78590d-0a2b-4fea-8d7e-ef95ca96fd95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
