<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3_2_select_Pilih Tujuan Pembukaan RekeningInves_a44001</name>
   <tag></tag>
   <elementGuidId>cb3c3528-b8d3-4f18-afeb-33f1a38dc3f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div[2]/div[4]/div/div[1]/div/div/div[1]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'onboardPermitsDto.openAccountGoal' and (text() = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi' or . = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi') and @option = 'Investasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tujuan Pembukaan Rekening&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4dd437d1-7c9a-4c33-96ac-ef46d138e11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardPermitsDto.openAccountGoal</value>
      <webElementGuid>441c9344-f4cb-4bbf-bf0a-89007cedaa67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardPermitsDto.openAccountGoal</value>
      <webElementGuid>99984cd7-5d3a-4554-a2a8-5be4228afe78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>19424cb9-b224-4d83-9250-2330a2078e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi</value>
      <webElementGuid>253dd836-e724-4e23-85a4-15a23234ce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardPermitsDto.openAccountGoal&quot;)</value>
      <webElementGuid>a351080e-ce5b-4b94-a1f3-9c9d4b8a35b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option</name>
      <type>Main</type>
      <value>Investasi</value>
      <webElementGuid>0d420412-6bf9-47d6-bb1e-0c37963f76e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardPermitsDto.openAccountGoal']</value>
      <webElementGuid>c57962e7-5119-4f5d-8aec-5f0b07049688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div[2]/div[4]/div/div/div/div/div/select</value>
      <webElementGuid>67f6fc19-f45a-460d-b1ea-195eba9a85e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan Pembukaan Rekening'])[1]/following::select[1]</value>
      <webElementGuid>86647937-3c01-4849-b6bc-0963df3b7393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Memiliki Giro'])[1]/following::select[1]</value>
      <webElementGuid>32497fba-44e9-4a2e-890f-cbd36f09b4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro Rupiah'])[1]/preceding::select[1]</value>
      <webElementGuid>20bee7e5-170e-456c-b61a-a92ea08f9677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro Valas'])[1]/preceding::select[1]</value>
      <webElementGuid>ec0011db-2dad-4ceb-bd88-0493ca4d077c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1965341d-ccc2-4361-8bb2-53a05ef27ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardPermitsDto.openAccountGoal' and @id = 'onboardPermitsDto.openAccountGoal' and (text() = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi' or . = 'Pilih Tujuan Pembukaan RekeningInvestasiSimpananTransaksi')]</value>
      <webElementGuid>2d072100-3e2e-4ad5-86fd-7982798f99f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
