<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3_3_button_Giro Rupiah</name>
   <tag></tag>
   <elementGuidId>d77ad137-2379-4869-be24-b1a757e88aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and (text() = 'Giro Rupiah' or . = 'Giro Rupiah')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div[2]/div[3]/div/div[3]/div/button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-1mc1s4p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Giro Rupiah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05a9fbd8-5aa3-479a-a4c7-8c76a72d0d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ab36a446-0c4b-45ea-aad9-99a08482108d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1mc1s4p</value>
      <webElementGuid>80fc620d-f066-4f4d-8ffd-40d309fa4994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giro Rupiah</value>
      <webElementGuid>c603df9c-ba71-42b3-a345-097c969bf2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-dw31nk&quot;]/div[@class=&quot;css-1noczd8&quot;]/div[@class=&quot;css-l4pxbn&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-button__group css-8z6n3j&quot;]/button[@class=&quot;chakra-button css-1mc1s4p&quot;]</value>
      <webElementGuid>979b90ef-607c-408b-ba94-9f0d1ea2df6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>39d739d5-1e32-4381-aa77-57df128bb6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[3]/div/div[3]/div/button</value>
      <webElementGuid>519aabce-2543-4371-8914-2b21dfa128f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Rekening'])[1]/following::button[1]</value>
      <webElementGuid>265489a3-1387-4fd0-8125-b74fad6133c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan Pembukaan Rekening'])[1]/following::button[1]</value>
      <webElementGuid>e88c7689-2145-492a-ab93-fd007211e42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro Valas'])[1]/preceding::button[1]</value>
      <webElementGuid>c6530171-1805-495d-b9e8-6fd678625466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::button[2]</value>
      <webElementGuid>b66e272c-cb00-4002-b23c-f04aa8145829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Giro Rupiah']/parent::*</value>
      <webElementGuid>cbbe2972-6fc0-49b0-92e8-b5542f0e9c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>e43442d6-aa5e-4035-9595-c1327cec80cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Giro Rupiah' or . = 'Giro Rupiah')]</value>
      <webElementGuid>aff09b72-c4e0-44c2-9b6e-65fd650227da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
