<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3_Select_Giro_Valas</name>
   <tag></tag>
   <elementGuidId>c209fcf1-418a-41dc-acd3-58a398392795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'onboardDto.currencyCode' and @name = 'onboardDto.currencyCode']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-30']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#react-select-2-option-30</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3e324409-8e1d-4d6a-8ddd-e7951404a540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.currencyCode</value>
      <webElementGuid>a1471033-5ed7-44d1-a8f2-c972200990ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.currencyCode</value>
      <webElementGuid>00c3072f-410c-49bb-9473-1d3a79aa93bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-30']</value>
      <webElementGuid>721d9610-5800-4df7-b49d-6e2e78b67ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div[31]</value>
      <webElementGuid>04bf9b84-404b-4bb3-ab05-e56be0072d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT'])[1]/following::div[1]</value>
      <webElementGuid>7e7aa812-8001-4a26-8077-1e7447b2c7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JETIS - KOMPLEKS NO.3-4, JL. RAYA CANGGU, KEC. JETIS, KAB. MOJOKERTO'])[1]/following::div[2]</value>
      <webElementGuid>30340052-09f3-4851-b781-b55e3745bf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT'])[3]/preceding::div[1]</value>
      <webElementGuid>0ad9da00-f958-4d3d-b8fc-a4c3260ee950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SETRASARI - JL. PROF. DRG. SURYA SUMANTRI NO.8B, KEL. SUKAWARNA, KEC. SUKAJADI, KOTA BANDUNG'])[1]/preceding::div[2]</value>
      <webElementGuid>fbdecf91-b335-4cb8-9407-6698ac262368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]</value>
      <webElementGuid>b93b987b-896a-454c-afcf-d8e682a24e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-30' and (text() = 'JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT' or . = 'JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT')]</value>
      <webElementGuid>103837b2-eb9b-492f-acdf-643f41e14ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
