<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4.1_div_Pejabat Yang BerwenangADARTPihak Yang D_ecdd34</name>
   <tag></tag>
   <elementGuidId>5dcdcb2c-827d-422c-b365-41f7939c27fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Pejabat Yang BerwenangAD/ARTPihak Yang Diberikan Kuasa' or . = 'Pejabat Yang BerwenangAD/ARTPihak Yang Diberikan Kuasa')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/following::div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1j1i25b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pejabat Yang BerwenangAD/ARTPihak Yang Diberikan Kuasa&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cc9023e-f3de-457a-971d-20cdf70f7e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1j1i25b</value>
      <webElementGuid>3b97aa38-9ca7-45a9-a4b1-75f4c372a14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pejabat Yang BerwenangAD/ARTPihak Yang Diberikan Kuasa</value>
      <webElementGuid>3116cafa-822d-46dc-8b19-c996026ddd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-1gtf5cl&quot;]/div[@class=&quot;css-1j1i25b&quot;]</value>
      <webElementGuid>85194382-36a2-4acb-80c8-4613739d0be2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>05b431c4-4da7-4c41-bc64-d132f3fbee72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/following::div[4]</value>
      <webElementGuid>c1aa73f3-3626-453e-98cc-94e9dda681f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/following::div[72]</value>
      <webElementGuid>e3f2d959-0e08-4c95-a3ae-950dbc90e57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>d6a1e993-5852-4344-88fc-a23cc5ba86a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pejabat Yang BerwenangAD/ARTPihak Yang Diberikan Kuasa' or . = 'Pejabat Yang BerwenangAD/ARTPihak Yang Diberikan Kuasa')]</value>
      <webElementGuid>8f975a97-7216-49f0-9a5f-b311c9619ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
