<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>6.12_input_Persentase Pelanggan Domestik</name>
   <tag></tag>
   <elementGuidId>45aed8f4-ed28-4abb-9353-82c2eb5dc318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'onboardDto.domesticCustomerPct' and @placeholder = 'Masukkan Persentase Pelanggan Domestik' and @type = 'number' and @id = 'onboardDto.domesticCustomerPct']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;onboardDto.domesticCustomerPct&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Persentase Pelanggan Domestik&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68eade12-2eec-40ef-bf72-12b325f7e91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.domesticCustomerPct</value>
      <webElementGuid>0dcf758a-d4c8-4248-8ee9-d6a90776cf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Persentase Pelanggan Domestik</value>
      <webElementGuid>3497c1d3-4665-4464-b641-5bfbd242406f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3f8954d7-ad9c-4243-b08c-09360625687a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.domesticCustomerPct</value>
      <webElementGuid>9905266a-7e26-4dd4-b3ad-2cff746da7e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onboardDto.domesticCustomerPct']</value>
      <webElementGuid>0b9ef73b-fcf3-42e5-98f1-34b362129d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[12]/input</value>
      <webElementGuid>6493a408-5b77-4b9d-a450-0e9072e7eacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input</value>
      <webElementGuid>86932a80-e5f2-41bd-8dff-6b52cdd9f717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'onboardDto.domesticCustomerPct' and @placeholder = 'Masukkan Persentase Pelanggan Domestik' and @type = 'number' and @id = 'onboardDto.domesticCustomerPct']</value>
      <webElementGuid>806202e6-d8f9-416e-8d58-dda6e617798b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
