<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>6.2_input_Nama Perusahaan</name>
   <tag></tag>
   <elementGuidId>8cc6d65a-c3ab-49fd-8c02-c1f0db79eb28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@placeholder = 'Masukkan Nama Perusahaan' and @type = 'text' and @id = 'onboardDto.compName']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Nama Perusahaan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d7594f8-0cde-438a-afee-facefa237b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Perusahaan</value>
      <webElementGuid>35e7ea5d-10cd-4c90-9a8a-0cb4fba6f1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe1fe326-061b-4d7b-a55a-1b4487594665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compName</value>
      <webElementGuid>51c148cd-717f-40c9-a135-5f5f27c9d4ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onboardDto.compName']</value>
      <webElementGuid>9bfa4674-7d64-44dc-b59b-aeae3edb0dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>1952b3c7-d800-40b5-8354-d61a0c6d5112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e6c36254-97ed-4074-83fa-aa9ae05c72c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'onboardDto.compName' and @placeholder = 'Masukkan Nama Perusahaan' and @type = 'text' and @id = 'onboardDto.compName']</value>
      <webElementGuid>4f3df2ef-888f-4cee-8432-fe0451e4f558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
