<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>6.7_button_Indonesia</name>
   <tag></tag>
   <elementGuidId>cf52fdc5-386b-4cd5-90da-e0c30e93e057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[7]/div/div/div/label[1]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-p8q84w</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Indonesia&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7230d57-4220-4e36-9056-85d35f529568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6</value>
      <webElementGuid>d50d65e2-8fb4-4233-bcb1-f67ff2d6e5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>6952f30b-88db-4b58-9323-b3aeaf2c1ac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>c1112476-54dc-456c-a979-970546c47a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[3]/div[12]/button</value>
      <webElementGuid>e54f2555-a904-4aec-972f-38eac3ba7769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kependudukan'])[1]/following::button[1]</value>
      <webElementGuid>55ca0246-48fe-4882-b457-c16700142b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Karyawan'])[1]/following::button[1]</value>
      <webElementGuid>3acf298a-3cc1-44a4-b684-44f15539134d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luar Negeri'])[1]/preceding::button[1]</value>
      <webElementGuid>ff6bbd9d-02e6-4bae-ad28-331f6216d424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/button</value>
      <webElementGuid>f8632f7f-5d78-41ff-9843-b3ea72cc0b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>ac8eef78-3f47-40f4-ab41-1c408510c340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
