<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>7.6_select_Pilih KecamatanGrogol</name>
   <tag></tag>
   <elementGuidId>cddac7fe-06b5-4841-90c3-63998f5f036e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='field-:rj:'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;onboardDto\.districtId&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f35a3387-39a7-48fe-9bbe-25ab3b06df31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.districtId</value>
      <webElementGuid>cf6a0805-1af1-4c0e-8885-1b15e074dea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rj:</value>
      <webElementGuid>743b8984-2bf3-49d7-9a11-62434dffa5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-l1m0k1</value>
      <webElementGuid>b8440319-a303-40e1-bf6f-217a37a5b27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KecamatanGrogol PetamburanKalideresKebon JerukPalmerahTaman SariCengkarengKembanganTambora</value>
      <webElementGuid>d84532d1-85b4-4d20-bd07-8b7331e1c850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-select__wrapper css-15ca0qf&quot;]/select[@id=&quot;field-:rj:&quot;]</value>
      <webElementGuid>fa958474-6a20-42b2-825f-adb7c5197dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='field-:rj:'])[4]</value>
      <webElementGuid>5e2316a0-2f12-433d-9e8d-535c147c5ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[2]/div[5]/div/select</value>
      <webElementGuid>d885d057-437d-4a9f-a2ee-030ec589a21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>7dd3241f-c431-4942-a953-6321aa66a5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Kelurahan'])[1]/preceding::select[1]</value>
      <webElementGuid>13ad44f6-fa04-44ea-bbb8-bcfb5b4b1e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>d0d39d04-6365-4e03-97df-9db2d541bb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.districtId' and @id = 'field-:rj:' and (text() = 'Pilih KecamatanGrogol PetamburanKalideresKebon JerukPalmerahTaman SariCengkarengKembanganTambora' or . = 'Pilih KecamatanGrogol PetamburanKalideresKebon JerukPalmerahTaman SariCengkarengKembanganTambora')]</value>
      <webElementGuid>e0181c48-74c0-4a22-8228-faae8a8ff9af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
