<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8.3_input_Tempat Dikeluarkan Identitas_onboardP_54807e</name>
   <tag></tag>
   <elementGuidId>588421be-6911-43e9-95ba-a508b084b338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='onboardPermitsDto.idPlaceIssued']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan tempat dikeluarkan identitas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2f0eb94-9f9f-4078-bfc4-07b0b77c03ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardPermitsDto.idPlaceIssued</value>
      <webElementGuid>359bf689-51ba-4eb6-b355-38d1c4d4bccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan tempat dikeluarkan identitas</value>
      <webElementGuid>6941a7ec-30a3-4357-be00-51d839518005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84d00cc2-48e3-4065-95fc-c2c6909c564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] px-4 py-2 text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-kxju8z</value>
      <webElementGuid>344ea13d-9dc9-4965-bdba-4d8c05863aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardPermitsDto.idPlaceIssued</value>
      <webElementGuid>5b489f82-d88c-49b0-a60a-a7e6f4c193a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardPermitsDto.idPlaceIssued&quot;)</value>
      <webElementGuid>21229895-fd9f-4dcc-b3fc-5ae464fac747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onboardPermitsDto.idPlaceIssued']</value>
      <webElementGuid>a96f123a-ad78-42be-a737-7c5b77d1a1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[3]/input</value>
      <webElementGuid>8c41c442-1b83-4e77-af83-8bda20babba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>51b957b4-3d9c-4466-8340-dbdfcf131a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'onboardPermitsDto.idPlaceIssued' and @placeholder = 'Masukkan tempat dikeluarkan identitas' and @type = 'text' and @id = 'onboardPermitsDto.idPlaceIssued']</value>
      <webElementGuid>87c96d39-91f1-40b9-8b73-0cc7e79d6c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
