<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Up</name>
   <tag></tag>
   <elementGuidId>bbd248f7-990a-46ae-8c44-d9c0b950182c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Sign Up Now' or . = 'Sign Up Now')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[1]/div[1]/div[1]/div[4]/a/button</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Register Now&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dca6cfe-4aa0-4487-bdb4-b392fe2b22df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46773a41-3807-4fe1-8697-809e05aa0dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button justify-center self-start px-5 py-3 mt-6 text-base font-semibold leading-6 text-white whitespace-nowrap bg-orange-400 rounded-full border border-solid shadow-sm border-[color:var(--Colors-Text-text-brand-primary,#FF8736)] css-wbiuu4</value>
      <webElementGuid>731a8939-6df1-45ee-8380-e7019425859b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up Now</value>
      <webElementGuid>a9a7e536-edb8-4f58-90a7-0778c66bacab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/div[@class=&quot;css-13w3gmp&quot;]/div[@class=&quot;flex relative flex-col flex-1 my-auto max-md:max-w-full css-0&quot;]/a[1]/button[@class=&quot;chakra-button justify-center self-start px-5 py-3 mt-6 text-base font-semibold leading-6 text-white whitespace-nowrap bg-orange-400 rounded-full border border-solid shadow-sm border-[color:var(--Colors-Text-text-brand-primary,#FF8736)] css-wbiuu4&quot;]</value>
      <webElementGuid>cd754959-564b-4d44-b3b2-1557f0c0d542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>8a1bc928-b38d-459f-b15f-2860cb00c5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/a/button</value>
      <webElementGuid>07eba3c5-ef0b-4584-b17c-ffb74cc28420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple, transparent banking. All in one platform.'])[1]/following::button[1]</value>
      <webElementGuid>c5ad2394-1deb-4717-80cb-1a12dec7935e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Best Corporate Banking for your business'])[1]/following::button[1]</value>
      <webElementGuid>0cac0e5e-79b8-48a7-90c9-8c2c8f90a666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products Wholesale'])[1]/preceding::button[1]</value>
      <webElementGuid>d6c06e9f-ecbe-4393-83fe-7a97268a9dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro'])[1]/preceding::button[1]</value>
      <webElementGuid>0d7266e4-22ce-4889-8846-590b10757e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register Now']/parent::*</value>
      <webElementGuid>6004a48c-4893-4155-a69a-23eb48b6c0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a/button</value>
      <webElementGuid>c489c6af-a2a3-4635-80b6-fabc8d73afa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Register Now' or . = 'Register Now')]</value>
      <webElementGuid>e3785c3b-fdd5-4cff-9eea-7e5533a982ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
