<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Klik untuk upload atau drag and dropFor_408759</name>
   <tag></tag>
   <elementGuidId>9bbe5234-7212-4796-8bf7-a55d2e7dd723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[14]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-dvxtzn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-dvxtzn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0e68eb8-6ca2-408e-a957-27dcfb9ae5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-dvxtzn</value>
      <webElementGuid>8d9ff78e-bb59-42ee-8866-f042abe36a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Klik untuk upload atau drag and dropFormat PDF [max. 1Mb]</value>
      <webElementGuid>39fcabf2-836d-4cbb-93e3-545b076a730f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-1gtf5cl&quot;]/label[14]/div[@class=&quot;css-1n9kzij&quot;]/div[@class=&quot;css-dvxtzn&quot;]</value>
      <webElementGuid>66acf9e4-ede7-4969-bdfd-eab6642dc5eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[14]/div/div</value>
      <webElementGuid>32de5c25-2472-48d4-9e3d-e788e536a440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KTP'])[1]/following::div[2]</value>
      <webElementGuid>191d8007-66ed-411c-96b3-d8732a96a41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akta Perubahan Terakhir'])[1]/following::div[8]</value>
      <webElementGuid>04a4aa9f-b858-4fd0-9a23-03ccf8fabdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[14]/div/div</value>
      <webElementGuid>6895b2d2-1360-47b0-9363-6b7c02b5cf2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Klik untuk upload atau drag and dropFormat PDF [max. 1Mb]' or . = 'Klik untuk upload atau drag and dropFormat PDF [max. 1Mb]')]</value>
      <webElementGuid>340731f3-39c6-4a06-8373-8f32232af29c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
