<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JELAMBAR BARU - JL. JELAMBAR BARU RAYA _00a004</name>
   <tag></tag>
   <elementGuidId>f0c97bff-2d01-4252-a566-5801b7bccaf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-30</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@aria-activedescendant = 'react-select-3-option-29']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#react-select-2-option-30</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e724474-c89c-470c-8f06-62acdd20fa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1czt1k7-option</value>
      <webElementGuid>26216d36-9a2f-4900-ac79-4ff1ecf94ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ea408da-45a1-44ea-b5c2-300655864155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>react-select-3-option-29</value>
      <webElementGuid>14c5f90e-ff8e-4b61-a2f9-4e4789a6b430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>740c8fc8-d84e-4544-9ce0-564659312988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bbc08071-ff18-4cd0-a09a-33f2201e426d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b21a8ab-ffb6-4e5c-bb98-3150f88b1167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT</value>
      <webElementGuid>60a2eef3-3bb7-4cee-b674-4a88fa9989ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-30&quot;)</value>
      <webElementGuid>353258c5-b0b5-453f-bb91-70e037f339f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-30']</value>
      <webElementGuid>6d118657-5853-4e44-9edb-681c45746388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div[31]</value>
      <webElementGuid>22a6c375-e806-48cb-b97f-c55fd6731e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT'])[1]/following::div[1]</value>
      <webElementGuid>226ff8ae-b374-4e2d-954b-da2fe0977923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JETIS - KOMPLEKS NO.3-4, JL. RAYA CANGGU, KEC. JETIS, KAB. MOJOKERTO'])[1]/following::div[2]</value>
      <webElementGuid>0622ac39-5e30-493e-a6c5-11b34e9eb70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT'])[3]/preceding::div[1]</value>
      <webElementGuid>61316627-c65a-4cfb-bac0-6c9f1061e7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SETRASARI - JL. PROF. DRG. SURYA SUMANTRI NO.8B, KEL. SUKAWARNA, KEC. SUKAJADI, KOTA BANDUNG'])[1]/preceding::div[2]</value>
      <webElementGuid>2f67af37-2d18-409c-b9f1-21e59111e954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]</value>
      <webElementGuid>a339f76e-3dbe-46e5-99ad-67a0f5dd7afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-30' and (text() = 'JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT' or . = 'JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT')]</value>
      <webElementGuid>9e25450e-95b5-40f8-87d1-aab9ce679107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
