<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JAKARTA PUSAT - JL. JEND. SUDIRMAN KAV._3d0eb9</name>
   <tag></tag>
   <elementGuidId>02402649-5873-4432-861f-410c69f7dbae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#react-select-2-option-19</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ddcae88-414f-467a-8feb-be7a655c0832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-f85sjx-option</value>
      <webElementGuid>33d98793-6078-4cb3-8a79-d8164040fb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>33624d75-543c-4987-8fcc-d3f626f95af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-19</value>
      <webElementGuid>81f20a3e-6119-4523-a870-10d208e004fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3b6a5e16-05e2-4996-8c92-be20d8537fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1ac6d56d-a914-47d3-81b4-ef807600c07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>517bd1f4-1b2c-4db3-b732-5634c9485800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JAKARTA PUSAT - JL. JEND. SUDIRMAN KAV.1 , JAKARTA PUSAT</value>
      <webElementGuid>b5d540ef-4917-4589-96e8-bb5af761efea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-19&quot;)</value>
      <webElementGuid>687b4c09-b407-4cc2-91ff-7d723e506f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-19']</value>
      <webElementGuid>54228d53-a252-4e13-80dc-e20918c94335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div[20]</value>
      <webElementGuid>508ce926-aac3-4844-b61f-674c9178af93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIDOARJO - JL.JENGGOLO NO. 47 - 51, SIDOARJO'])[1]/following::div[1]</value>
      <webElementGuid>ebdc59ec-0a3e-4739-a3f4-73d49639b03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='null - null'])[8]/following::div[2]</value>
      <webElementGuid>f65408db-e3c3-45cc-b48b-4471ce2fb91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAKARTA PUSAT - JL. JEND. SUDIRMAN KAV.1 , JAKARTA PUSAT'])[2]/preceding::div[1]</value>
      <webElementGuid>88bea283-f1aa-4a60-a3f0-5777755ed1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAKARTA PUSAT - JL. JEND. SUDIRMAN KAV.1 , JAKARTA PUSAT'])[3]/preceding::div[2]</value>
      <webElementGuid>efa7cfcd-471c-4e6e-a9a3-9892a09c799a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JAKARTA PUSAT - JL. JEND. SUDIRMAN KAV.1 , JAKARTA PUSAT']/parent::*</value>
      <webElementGuid>b8f59531-5a1d-4493-bedd-6cff67222fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]</value>
      <webElementGuid>be4a9b87-e8ed-4e74-a325-4b4e7b7920e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-19' and (text() = 'JAKARTA PUSAT - JL. JEND. SUDIRMAN KAV.1 , JAKARTA PUSAT' or . = 'JAKARTA PUSAT - JL. JEND. SUDIRMAN KAV.1 , JAKARTA PUSAT')]</value>
      <webElementGuid>d04649a2-d561-4410-8ec8-ae6a636dbfe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
