<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__css-3ff64v</name>
   <tag></tag>
   <elementGuidId>e4bfe8b1-02f7-407e-82ae-62548dea6fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[4]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-3ff64v</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-3ff64v</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43f47f5c-4369-404d-bb2a-0f30ddedf714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-3ff64v</value>
      <webElementGuid>79256bfb-fc36-4e34-9214-30c7ab478428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-1gtf5cl&quot;]/label[4]/div[@class=&quot;css-1n9kzij&quot;]/div[@class=&quot;css-dvxtzn&quot;]/div[@class=&quot;css-3ff64v&quot;]</value>
      <webElementGuid>dcc4df32-5a55-406d-92f8-00aeb6cd477d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[4]/div/div/div</value>
      <webElementGuid>b4658ed9-f339-4ea3-ac1a-e8ab23c43eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[3]</value>
      <webElementGuid>10a414ca-8df8-46e0-adda-50a2c4bad99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klik untuk upload'])[1]/preceding::div[1]</value>
      <webElementGuid>53858c40-31f8-49d0-aeeb-9eb615472fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/div/div/div</value>
      <webElementGuid>faea8365-2a03-4800-8240-dfb8f30774ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
