<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Indonesia</name>
   <tag></tag>
   <elementGuidId>6c6457f6-cdaa-488c-b4b3-e9c956e47c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[7]/div/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Indonesia&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a86501a-4b15-4df7-a9df-5aa0475952b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6</value>
      <webElementGuid>1d4cad09-8ad2-49cc-b53b-52cec2b82d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>a8b5b075-a9f0-4976-a50a-fbebecb0ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-h7lv1c&quot;]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1j1i25b&quot;]/div[1]/div[@class=&quot;css-16bqc1g&quot;]/label[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6&quot;]</value>
      <webElementGuid>7be6c48a-d524-40a2-8ac5-35a0d2c98a69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[7]/div/div/label/div</value>
      <webElementGuid>00d7f297-55c8-4f7e-88a3-43d2f5926e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Karyawan'])[1]/following::div[5]</value>
      <webElementGuid>0298e751-4380-451b-a0aa-6e2bcde00055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luar Negeri'])[1]/preceding::div[1]</value>
      <webElementGuid>c52ee0da-8781-434f-9b09-f4116cf78105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/preceding::div[2]</value>
      <webElementGuid>7172af37-bba2-43c1-9d85-454dc5d1182b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indonesia']/parent::*</value>
      <webElementGuid>f786d4fe-f5e0-47bb-9ad0-f6af7bc94d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>d365850e-d27b-4fb7-994e-2324bd724fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>cbe600a5-6c93-48b6-83e1-6859da0c8555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
