<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JELAMBAR BARU - JL. JELAMBAR BARU RAYA _00a004 - Copy</name>
   <tag></tag>
   <elementGuidId>72d523d4-7d75-4273-86d8-d8b1c875ccdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-30']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#react-select-2-option-30</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a61d1bb7-0dc7-406d-a88b-94910cd7a177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1czt1k7-option</value>
      <webElementGuid>7f93c467-506b-4fa6-9a3d-d1ea608f3d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cbd5b6e5-6f02-491a-8f6f-7477f92dd51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-30</value>
      <webElementGuid>0ae187f8-aa9a-4d16-8612-d8c78ba562c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>be698a70-5057-4d72-aef8-83eb240fed82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0fa0908d-56c0-44a3-bff0-2db5c585a7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc5847a8-c52e-4354-bdbe-9798626e5fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT</value>
      <webElementGuid>1d71453f-8477-4628-9720-8cd2ec44df85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-30&quot;)</value>
      <webElementGuid>990f73e3-11d8-46ed-8f68-a083ad9de066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-30']</value>
      <webElementGuid>331fe7e1-5403-437b-a87f-e4d950f34c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']/div[31]</value>
      <webElementGuid>13bce50e-61d2-43b4-98e9-4a783a3b4d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT'])[1]/following::div[1]</value>
      <webElementGuid>cd737d4e-80fa-4479-9ca3-0cf942b9788a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JETIS - KOMPLEKS NO.3-4, JL. RAYA CANGGU, KEC. JETIS, KAB. MOJOKERTO'])[1]/following::div[2]</value>
      <webElementGuid>ad8f2562-3fa7-4d53-8fe4-fd5cdabd9f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT'])[3]/preceding::div[1]</value>
      <webElementGuid>4030951a-9a2d-4ffb-9cbd-db1dd6f7d4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SETRASARI - JL. PROF. DRG. SURYA SUMANTRI NO.8B, KEL. SUKAWARNA, KEC. SUKAJADI, KOTA BANDUNG'])[1]/preceding::div[2]</value>
      <webElementGuid>9a3c5acd-cf52-4e9d-9f49-68d6f39051e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]</value>
      <webElementGuid>0dc1a750-a309-4f4f-be89-009c87b677a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-30' and (text() = 'JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT' or . = 'JELAMBAR BARU - JL. JELAMBAR BARU RAYA NO.23B KEL. JELAMBAR, KEC. GROGOL PETAMBURAN, JAKARTA BARAT')]</value>
      <webElementGuid>f5689498-dbdb-4ce8-ae5c-d2689d3db865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
