<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Akte  PerijinanNPWPNPWP harus 16 digitT_ddb055</name>
   <tag></tag>
   <elementGuidId>64ec8390-744a-4f71-b95a-c16868d0abe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-q2icr7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-q2icr7</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a29242e6-0d7e-48e8-88fd-37b4226f6a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-q2icr7</value>
      <webElementGuid>48462603-e184-4378-af6b-6e9b12d93fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akte &amp; PerijinanNPWP*NPWP harus 16 digitTempat Dikeluarkan IdentitasNomor Akte Pengesahan*Tanggal Pengesahan*Nomor Akte Pendirian/Anggaran Dasar*Tanggal Pendirian*Nama Notaris*Tempat Akte Dibuat*Nomor Akte PerubahanTanggal PerubahanNotarisNomor Izin Usaha / NIB*Tanggal Pembuatan*Tanggal ExpiredSelanjutnya</value>
      <webElementGuid>ee8206b1-6caf-4332-b7c2-784caa9a052f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]</value>
      <webElementGuid>febfa712-1307-474f-85a9-82039ff02e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div</value>
      <webElementGuid>7b29b039-1ece-4a02-b7af-57a0bc559757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::div[1]</value>
      <webElementGuid>ca5bfd6c-8a92-4403-9cfe-0f2252d166d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pernyataan &amp; Syarat Ketentuan'])[1]/following::div[4]</value>
      <webElementGuid>bbce8d79-f9f1-4cb0-8cc1-631019a558f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>de2bdd52-562d-4350-8522-d7e4c6e71327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Akte &amp; PerijinanNPWP*NPWP harus 16 digitTempat Dikeluarkan IdentitasNomor Akte Pengesahan*Tanggal Pengesahan*Nomor Akte Pendirian/Anggaran Dasar*Tanggal Pendirian*Nama Notaris*Tempat Akte Dibuat*Nomor Akte PerubahanTanggal PerubahanNotarisNomor Izin Usaha / NIB*Tanggal Pembuatan*Tanggal ExpiredSelanjutnya' or . = 'Akte &amp; PerijinanNPWP*NPWP harus 16 digitTempat Dikeluarkan IdentitasNomor Akte Pengesahan*Tanggal Pengesahan*Nomor Akte Pendirian/Anggaran Dasar*Tanggal Pendirian*Nama Notaris*Tempat Akte Dibuat*Nomor Akte PerubahanTanggal PerubahanNotarisNomor Izin Usaha / NIB*Tanggal Pembuatan*Tanggal ExpiredSelanjutnya')]</value>
      <webElementGuid>b3649f10-5b4d-48b6-95ac-c4b306cc6f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
