<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__namaPejabat - Copy (1)</name>
   <tag></tag>
   <elementGuidId>3791d9fe-c9eb-485b-99cf-d0b01a9a7872</elementGuidId>
   <imagePath>Screenshots/Targets/Page_BNIDirect/input__namaPejabat.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'namaPejabat' and @placeholder = 'Masukkan nama lengkap sesuai identitas' and @id = 'field-:rb:']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_BNIDirect/input__namaPejabat.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan nama lengkap sesuai identitas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4b7cc45-bf6c-4f07-820b-4d6d8bb3a247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>665b863c-d37a-4211-bc8c-e9c4b7d7155e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namaPejabat</value>
      <webElementGuid>aad623a5-b49e-4041-a559-82b40f3bd38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama lengkap sesuai identitas</value>
      <webElementGuid>885417e2-9db7-4291-8242-686b5f35b81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rb:</value>
      <webElementGuid>f0d32ae8-b0ce-4859-a43b-7df62c92b225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-10ex9a1</value>
      <webElementGuid>5024c5d2-6ec0-46dd-b53b-9d322affc845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]/div[@class=&quot;css-11b5mf8&quot;]/div[@class=&quot;css-u6v8er&quot;]/div[@class=&quot;css-cakzji&quot;]/form[1]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-1pf2w37&quot;]/form[1]/div[1]/input[@id=&quot;field-:rb:&quot;]</value>
      <webElementGuid>6041fd55-18c8-4522-b313-6fe520cf6c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-:rb:']</value>
      <webElementGuid>f1d4d41d-19a7-41c1-95c7-a04ee6609883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/form/div/div[2]/form/div/input</value>
      <webElementGuid>bdcb964d-3df9-4121-bdb8-90fd5cc8a9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>769d6f99-0882-46da-8c74-2f2dabb080ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'namaPejabat' and @placeholder = 'Masukkan nama lengkap sesuai identitas' and @id = 'field-:rb:']</value>
      <webElementGuid>5a0441c4-ce8e-4f74-b158-ee55480acba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
