<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Handphone_usersDto.makerDto.0.p_729376 - Copy (1)</name>
   <tag></tag>
   <elementGuidId>9fe4c596-70b1-4d3c-96fd-8bac58551f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usersDto.makerDto.0.phoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan nomor handphone&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee452c2f-9693-4fbb-9581-fb46066c39c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>usersDto.makerDto.0.phoneNumber</value>
      <webElementGuid>21032055-6be1-4689-b9dd-69be9b81543c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nomor handphone</value>
      <webElementGuid>c2318ae7-25d0-44a3-b510-c3a0f40d2c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0cca98b-5576-43dc-bb8c-c75bed2de54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] px-4 py-2 text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-kxju8z</value>
      <webElementGuid>9bb29399-c538-49d4-b345-1156e473c8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usersDto.makerDto.0.phoneNumber</value>
      <webElementGuid>81ef5a45-d5ed-4e70-bf0b-740d4919d31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usersDto.makerDto.0.phoneNumber&quot;)</value>
      <webElementGuid>331c3056-7330-4e33-84ab-059330c48600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usersDto.makerDto.0.phoneNumber']</value>
      <webElementGuid>09432812-d6f5-4a18-b6a5-824027a6c3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[3]/div/div/div[3]/input</value>
      <webElementGuid>bd00d4d1-1d0c-42aa-bab3-645a9d087cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>578911c9-69f7-4e96-bb90-2d79d6dbceb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'usersDto.makerDto.0.phoneNumber' and @placeholder = 'Masukkan nomor handphone' and @type = 'text' and @id = 'usersDto.makerDto.0.phoneNumber']</value>
      <webElementGuid>49789f3a-b238-4f1c-aa98-cc3448505401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
