<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tempat Dikeluarkan Identitas - Copy</name>
   <tag></tag>
   <elementGuidId>0dd7748e-5859-4d59-af24-0c59d83289f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='field-:rp:-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tempat Dikeluarkan Identitas&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8c6c3c54-86bf-4416-8d91-e03af8c5418c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>onboardPermitsDto.idPlaceIssued</value>
      <webElementGuid>1328f80b-ff85-43b5-90d8-a27662cb14a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rp:-label</value>
      <webElementGuid>304d6666-dd8b-4bd1-b008-2458d1dc5381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__label css-zzpmjs</value>
      <webElementGuid>d7140dca-20ba-46d9-b060-d05ad3862cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tempat Dikeluarkan Identitas</value>
      <webElementGuid>18d03936-a2c4-4801-8033-0740533d6efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:rp:-label&quot;)</value>
      <webElementGuid>5a2c7d82-b413-4d2e-a285-ffd1eb8facae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='field-:rp:-label']</value>
      <webElementGuid>3e05bc27-176c-44dd-a40c-299c916cbf37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[3]/label</value>
      <webElementGuid>bb2a5dc2-6e21-41e2-b193-ad70caa3bf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Akte maksimal 16 digit'])[1]/following::label[1]</value>
      <webElementGuid>57a8e7ea-4126-4ad8-b6b6-883a71fde2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tempat Dikeluarkan Identitas']/parent::*</value>
      <webElementGuid>6e3fc881-7491-4a43-917c-b1779175a567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label</value>
      <webElementGuid>d99b2487-3e62-4582-83d3-489ff24cc137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'field-:rp:-label' and (text() = 'Tempat Dikeluarkan Identitas' or . = 'Tempat Dikeluarkan Identitas')]</value>
      <webElementGuid>f2c30262-2ec3-4ae3-8241-24f8f64787b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
