<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tanggal Pembuatan</name>
   <tag></tag>
   <elementGuidId>dc850293-e7d0-429b-9873-b0a521ad4085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='field-:r18:-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tanggal Pembuatan*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6cba4afa-902d-49a9-8b37-2489c03438ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>onboardPermitsDto.licenseIssueDate</value>
      <webElementGuid>eedd60f9-3d8b-4d74-8a5d-1c4b3845d268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r18:-label</value>
      <webElementGuid>bcd2731c-88c9-4b55-a0ba-c8051aba5162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form__label css-zzpmjs</value>
      <webElementGuid>56561c45-f070-4ab4-bd6a-2b61fe1cfe6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal Pembuatan*</value>
      <webElementGuid>dcc5950f-a00b-4031-b4bd-63b39c5518fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r18:-label&quot;)</value>
      <webElementGuid>15a897da-5a21-4389-bc9a-e4e5a5b02b40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='field-:r18:-label']</value>
      <webElementGuid>80f9af49-f64c-4140-91fb-cf48dbed6567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[14]/label</value>
      <webElementGuid>38d0770d-381a-4307-95e6-6fda387ad581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Ijin Usaha harus diisi'])[1]/following::label[1]</value>
      <webElementGuid>400b6af6-9ffd-4a20-9eba-57783b2a2afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous Month'])[1]/preceding::label[1]</value>
      <webElementGuid>5e06821d-c892-4d6c-990c-a065228d3077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 2024'])[1]/preceding::label[1]</value>
      <webElementGuid>de6fc378-c879-4122-8ca5-d91b91787e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tanggal Pembuatan']/parent::*</value>
      <webElementGuid>7cbe9e9f-47a4-4d8f-9dd9-061fe7b4094c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/label</value>
      <webElementGuid>ca3dfe07-9f92-4b04-be30-3711c29875b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'field-:r18:-label' and (text() = 'Tanggal Pembuatan*' or . = 'Tanggal Pembuatan*')]</value>
      <webElementGuid>98086a0b-5d35-49fa-bcaf-e0310860fe33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
