<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_071NIBHarusMemilikdigit</name>
   <tag></tag>
   <elementGuidId>8364b6f9-a836-4409-985c-db41e3dd7128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[13]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'NIB harus memiliki 13 digit' or . = 'NIB harus memiliki 13 digit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>00cce1b6-dbfc-4109-a51a-f2c3f5d7c9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIB harus memiliki 13 digit</value>
      <webElementGuid>bc0d41ee-228c-4cd8-9bd8-b640253de7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[13]/div[2]</value>
      <webElementGuid>90b8ddaf-1790-4d7e-af8a-308c352c838e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
