<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_056_NegaraKosong</name>
   <tag></tag>
   <elementGuidId>17c45c5e-d0f5-42ad-a1cc-74a20dc6dc06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[1]/div[2][count(. | //div[(text() = 'Negara harus dipilih' or . = 'Negara harus dipilih')]) = count(//div[(text() = 'Negara harus dipilih' or . = 'Negara harus dipilih')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9f7a597-500a-4d82-8c81-268b3dfe13b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Negara harus dipilih</value>
      <webElementGuid>7cf8067b-bc9c-444a-b70e-7e7530e15cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[1]/div[2]</value>
      <webElementGuid>c5131134-15d0-44dc-8285-f1b83725e39c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
