<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_094_JadwalKunjunganKosong</name>
   <tag></tag>
   <elementGuidId>2620f659-a6e3-4a99-9e36-28fade186525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[4]/div[2][count(. | //div[(text() = 'Tanggal harus dipilih' or . = 'Tanggal harus dipilih')]) = count(//div[(text() = 'Tanggal harus dipilih' or . = 'Tanggal harus dipilih')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[4]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3dcb5038-ae7d-4ff2-8caf-33c99b5970ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal harus dipilih</value>
      <webElementGuid>f1454b2c-96ad-4c39-9cc6-f965ab450ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[4]/div[2]</value>
      <webElementGuid>b89845f3-9bf8-4c1e-8ed4-b7abc32e82d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
