<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_060_KelurahanKosong</name>
   <tag></tag>
   <elementGuidId>fe2440f3-7135-463c-a718-583437105e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[7]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[7]/div[2][count(. | //div[(text() = 'Kelurahan harus dipilih' or . = 'Kelurahan harus dipilih')]) = count(//div[(text() = 'Kelurahan harus dipilih' or . = 'Kelurahan harus dipilih')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af7453ec-8fe2-4fca-99d6-c103f291af63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[7]/div[2]</value>
      <webElementGuid>afd131cd-3846-4641-891f-738b87417168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelurahan harus dipilih</value>
      <webElementGuid>658dda3d-3329-4b40-81ce-ee21dfa42ce1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
