<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>negative_TC_062_KodePosKosong</name>
   <tag></tag>
   <elementGuidId>de19f33f-10bb-4fc4-996a-d219703e379f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[3]/div[2][count(. | //div[(text() = 'Kode Pos harus diisi' or . = 'Kode Pos harus diisi')]) = count(//div[(text() = 'Kode Pos harus diisi' or . = 'Kode Pos harus diisi')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kode Pos harus diisi</value>
      <webElementGuid>5dbe13d4-22df-41d6-b288-e567cfcbbb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9ea683d-6d0a-41a6-b6ea-d05e8aa624a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[3]/div[2]</value>
      <webElementGuid>884a3378-0df6-458b-9bda-0aed0addd06f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
