<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>old_3_1_belum_punya_giro</name>
   <tag></tag>
   <elementGuidId>4335b86c-1a3f-4252-b21c-7243c080883f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div/form/div[2]/div[2]/div/div/div/div/label[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/form/div[2]/div[2]/div/div/div/label[2]/div[count(. | //div[(text() = 'Belum Memiliki Giro / Tabungan Bisnis' or . = 'Belum Memiliki Giro / Tabungan Bisnis') and @type = 'radio' and @name = 'onboardDto.isGiro' and @id = 'kepemilikanGiroFalse']) = count(//div[(text() = 'Belum Memiliki Giro / Tabungan Bisnis' or . = 'Belum Memiliki Giro / Tabungan Bisnis') and @type = 'radio' and @name = 'onboardDto.isGiro' and @id = 'kepemilikanGiroFalse'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum Memiliki Giro / Tabungan Bisnis</value>
      <webElementGuid>9fcc1a2b-5aa4-437f-b1fc-ba9b4b75c8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38c2b8c6-3af9-43f0-95f1-0624211d1c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1ec6654a-8040-4512-99a1-056cefe5503f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.isGiro</value>
      <webElementGuid>7290cbf2-30a2-4fd7-95f6-a33c7f9bb69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kepemilikanGiroFalse</value>
      <webElementGuid>96437425-3993-48a8-afdc-68ab19e5438a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/form/div[2]/div[2]/div/div/div/label[2]/div</value>
      <webElementGuid>69ca802c-dc7c-473c-9573-6f31d6bea8b2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
