<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tidak</name>
   <tag></tag>
   <elementGuidId>41b461a9-b907-4832-b3a6-64921ac95611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[8]/div/div/label[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tidak&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07d010da-5d64-4f9a-8781-7432e4046f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6</value>
      <webElementGuid>4290add6-9f1e-42df-bd0c-8323a4cfd155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tidak</value>
      <webElementGuid>20dccf18-eb08-408e-8360-0ccc06cea4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-h7lv1c&quot;]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1j1i25b&quot;]/div[1]/div[@class=&quot;css-16bqc1g&quot;]/label[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6&quot;]</value>
      <webElementGuid>39a58802-9258-460b-85fa-0d56354ef35a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[8]/div/div/label[2]/div</value>
      <webElementGuid>6dd25f52-4eb6-4988-81a0-c94060ee3082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/following::div[1]</value>
      <webElementGuid>d2309fc6-dd75-4d9b-af99-452db3bf016c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luar Negeri'])[1]/following::div[5]</value>
      <webElementGuid>77bb89fe-67f8-44e8-9f63-353ec7fa2d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak']/parent::*</value>
      <webElementGuid>647f29d4-1bf4-4337-ae4d-2eb7b4cf3508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/label[2]/div</value>
      <webElementGuid>c7cf9baa-233b-4820-8020-cf4358a5f462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tidak' or . = 'Tidak')]</value>
      <webElementGuid>6a6ae1fe-240d-4de1-987d-5e97c177cbe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
