<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jl. Kenari III_1</name>
   <tag></tag>
   <elementGuidId>4ab1eeb6-27ad-477e-9d88-e9cd5026421b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='onboardDto.compAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Alamat Lengkap&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6c9f5b8d-f50e-45fd-8f4f-798895b72d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>99ce2958-866b-454c-8e65-03b698b8d348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Lengkap</value>
      <webElementGuid>d288b67b-60de-4996-a276-59fe4ae99e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>39d3e791-739c-47f5-9b3d-b3b48310bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e024d841-3792-47a6-b299-b43a46516d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-textarea w-full bg-white border border-gray-300 hover:border-[#FF6B00] px-4 py-2 text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-31809p</value>
      <webElementGuid>3ac2db1e-0286-4c63-a6d0-5610eb3c4a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Kenari III </value>
      <webElementGuid>bdb2a7a1-6646-4539-8de4-2d9ca33ff0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.compAddress&quot;)</value>
      <webElementGuid>8daaa22b-f231-434e-a51f-bcb4119ad36c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='onboardDto.compAddress']</value>
      <webElementGuid>a47c9d4f-558f-42f3-8710-9b41822dd891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[4]/textarea</value>
      <webElementGuid>93324863-514c-4eb9-ac33-39bad11a1b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Email Perusahaan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d2691eb2-eecd-4aeb-abe1-fe021f0078cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jl. Kenari III']/parent::*</value>
      <webElementGuid>9511f352-0728-4014-821d-bba7e25d4d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>51bfba49-e75a-4e6f-a23a-7e547b00ebd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'onboardDto.compAddress' and @placeholder = 'Masukkan Alamat Lengkap' and @id = 'onboardDto.compAddress' and (text() = 'Jl. Kenari III ' or . = 'Jl. Kenari III ')]</value>
      <webElementGuid>4ced7d5a-0cb1-4326-af7b-10e871029cec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
