<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inquiry</name>
   <tag></tag>
   <elementGuidId>6b6a0a6d-10c9-4f03-bc4d-bbc57a81db05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-rtdrwe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Inquiry&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdaf869b-eea6-487e-bb83-00ecfa3c184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dbc2f3a-295b-4811-aed8-9f8627d009f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-rtdrwe</value>
      <webElementGuid>7cbec1ad-a9de-4275-8ae1-0d3524ab9228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inquiry</value>
      <webElementGuid>f34a8176-183b-4d85-bff9-0c53ebb72a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-11zqcuy&quot;]/div[@class=&quot;css-79kf1g&quot;]/div[@class=&quot;css-lacg&quot;]/form[1]/div[@class=&quot;chakra-form-control css-nftxoz&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-button__group css-8z6n3j&quot;]/button[@class=&quot;chakra-button css-rtdrwe&quot;]</value>
      <webElementGuid>82f463cc-3f0c-493e-a65b-eb6061f6c7c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>d70d9264-c814-43d5-b465-4ca8a0cbf257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div/form/div[2]/div/div/button</value>
      <webElementGuid>b6f6e704-2b7f-4aaa-9b4f-d8343d0c4d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktivitas Yang Anda Butuhkan Dalam Layanan Cash Management?'])[1]/following::button[1]</value>
      <webElementGuid>c0834a0e-43cc-4acb-9c3f-fdf72c3ecf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/following::button[1]</value>
      <webElementGuid>bba8da22-4904-4269-9614-9f52fd74ca25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inquiry + Transaksi'])[1]/preceding::button[1]</value>
      <webElementGuid>ad413cdf-3123-4179-accd-470ea6b1a000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda Ingin Mengelola User Administrator/Sysadmin?'])[1]/preceding::button[2]</value>
      <webElementGuid>5b6876ac-cdb6-46fe-ac28-502d8b91977e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inquiry']/parent::*</value>
      <webElementGuid>504826b1-7f08-4296-b8dd-a7bdd1a70bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>09ab6ee5-4856-423a-9e25-3acc2f007036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Inquiry' or . = 'Inquiry')]</value>
      <webElementGuid>35b6dd3e-abaa-48a3-8186-f254c7371182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
