<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nomor Izin Usaha  NIBNomor Ijin Usaha h_bd0fa5</name>
   <tag></tag>
   <elementGuidId>d958044d-865f-43d8-a18e-c5781a62d8a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[13]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nomor Izin Usaha / NIB*Nomor Ijin Usaha harus diisi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6885d6b-3fe4-4766-8d43-7061073f0885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>545c9aa5-4178-4d46-936f-2999cddd7152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-form-control css-vg05vg</value>
      <webElementGuid>1fb6a1b9-be6e-4ee5-bc6e-b96e8b9f6dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor Izin Usaha / NIB*Nomor Ijin Usaha harus diisi</value>
      <webElementGuid>c84ee19d-5b2c-49bb-857c-0c7784b1f5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-14a35dk&quot;]/div[@class=&quot;chakra-form-control css-vg05vg&quot;]</value>
      <webElementGuid>c7629371-21c9-449b-9d70-4532394052ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[13]</value>
      <webElementGuid>1c582f04-6ef1-4af0-89a2-4c6af0680831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notaris'])[1]/following::div[2]</value>
      <webElementGuid>732959e5-2118-4e4b-9b73-ad5381acd8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Perubahan'])[1]/following::div[8]</value>
      <webElementGuid>e33ed61a-c8d9-4680-ad77-25e730e0700e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]</value>
      <webElementGuid>e291ec83-a14e-4864-94cd-335256ce1990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nomor Izin Usaha / NIB*Nomor Ijin Usaha harus diisi' or . = 'Nomor Izin Usaha / NIB*Nomor Ijin Usaha harus diisi')]</value>
      <webElementGuid>8c4124b8-82ee-489a-a492-e66dd8db14c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
