<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ADART</name>
   <tag></tag>
   <elementGuidId>5954362e-dece-44de-9ba4-afb9c3f52eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[2]/div/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;AD/ART&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34aa7dad-5c41-423d-a592-bd20df98ef53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6</value>
      <webElementGuid>1e22e3d5-8253-4cc1-8540-3bf398358e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AD/ART</value>
      <webElementGuid>2d6210fa-5390-4106-8dab-544efd234425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-1gtf5cl&quot;]/div[@class=&quot;css-1j1i25b&quot;]/div[1]/div[@class=&quot;css-16bqc1g&quot;]/label[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;rounded-[99px] bg-white font-bold text-black ring-1 ring-[#BFC9D9] peer-checked:bg-[#FEF6EE] transition-all peer-checked:text-[#FF6B00] peer-checked:ring-[#FF6B00] peer-checked:ring-offset-2 py-1 px-6&quot;]</value>
      <webElementGuid>1ff62de5-ca5a-423e-99cd-69ecb640bb93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div[2]/div/div/label/div</value>
      <webElementGuid>b2edb613-038c-49a7-a443-0bc07958c5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/following::div[7]</value>
      <webElementGuid>3fe03e84-3fbd-4d21-a5d6-bbf8ef33ef09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/following::div[75]</value>
      <webElementGuid>d45bec69-94af-4672-a439-acc113e8720b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pihak Yang Diberikan Kuasa'])[1]/preceding::div[1]</value>
      <webElementGuid>61897b89-7993-4495-abca-92cebb02871b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AD/ART']/parent::*</value>
      <webElementGuid>4a41b5cd-b8b1-40dc-bb9a-60bdc5b420b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>58b51a93-e9e3-457d-a232-68efefb8e49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AD/ART' or . = 'AD/ART')]</value>
      <webElementGuid>ee2c791e-eff0-4259-a365-d3de32bde62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
