<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Klik untuk upload atau drag and dropFor_c29bdb</name>
   <tag></tag>
   <elementGuidId>bbcf66ea-62f0-44c6-979b-5fb78b09afd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[18]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-dvxtzn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG \(max\. 500kb\)$/ >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d25e6cf3-4273-429a-a1bc-884ed2967747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-dvxtzn</value>
      <webElementGuid>1769fbfb-0bd2-4d48-8221-f074f28f7e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG (max. 500kb)</value>
      <webElementGuid>fb51e17f-16e9-4454-9144-e152ce301558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-1gtf5cl&quot;]/label[18]/div[@class=&quot;css-1n9kzij&quot;]/div[@class=&quot;css-dvxtzn&quot;]</value>
      <webElementGuid>4cb3c66b-941e-42ab-8515-75b3e53d70a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/label[18]/div/div</value>
      <webElementGuid>0b2d2896-cf2d-4202-9bf5-79f122a38ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[2]</value>
      <webElementGuid>2e22bca9-8d90-4597-9b73-fc76aaa6b07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[18]/div/div</value>
      <webElementGuid>a96de2ce-4374-4007-bf8b-472983ada2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG (max. 500kb)' or . = 'Klik untuk upload atau drag and dropFormat PNG/SVG/JPG/JPEG (max. 500kb)')]</value>
      <webElementGuid>bb2fce14-4934-41c7-a0c9-af21821cba81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
