<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Pelanggan_onboardDto.customerCount</name>
   <tag></tag>
   <elementGuidId>6c0d687b-560f-4c1d-89dd-cd8213a4605e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='onboardDto.customerCount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Jumlah Pelanggan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7695770-6d42-4e1d-b8c6-8940e2592e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.customerCount</value>
      <webElementGuid>1defcdcb-6199-4b0e-a596-dc44a668358c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Jumlah Pelanggan</value>
      <webElementGuid>756264f7-a1b1-4cec-9d7a-ae0ea9e5a039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>83f4df6b-b098-4bc1-a4f4-99120748a1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] px-4 py-2 text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-kxju8z</value>
      <webElementGuid>33c84dc3-03d7-4a5a-bb8c-a1ff27419242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.customerCount</value>
      <webElementGuid>e0a80773-8e29-414b-b07c-c1a664530bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.customerCount&quot;)</value>
      <webElementGuid>1905cb27-8cc9-4112-808d-c7a6ae3b5769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='onboardDto.customerCount']</value>
      <webElementGuid>358aa016-2a00-4628-8b23-f22292004e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[11]/input</value>
      <webElementGuid>a61ab849-1888-4a04-8b08-29aa150c00b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>99a96e2b-9a2a-4a89-9497-4e2ca38a647a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'onboardDto.customerCount' and @placeholder = 'Masukkan Jumlah Pelanggan' and @type = 'number' and @id = 'onboardDto.customerCount']</value>
      <webElementGuid>0943a766-e47d-4dc0-8346-19413763d2b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
