<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Bentuk Badan UsahaPTBankKopera_6d3d37</name>
   <tag></tag>
   <elementGuidId>aa337a81-6255-441e-8512-e3ab95bb78a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='onboardDto.compEntityTypeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bentuk Badan Usaha*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a91458e6-f7d0-48e5-b871-16d9e1ea8e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compEntityTypeId</value>
      <webElementGuid>3ef1b257-5c10-47e0-aba0-6706d4d406f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compEntityTypeId</value>
      <webElementGuid>4cf72400-19d5-40c6-b4dc-d0768810ff68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6d941270-4af8-4ccd-980b-256cabf2ffaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>f90233d1-3479-4c2b-914a-ea8b916059fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA</value>
      <webElementGuid>6aa62c0b-dee1-43ea-88e5-377e96d3f730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.compEntityTypeId&quot;)</value>
      <webElementGuid>a80100e9-dccd-4ccc-bae5-419a82ae8333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardDto.compEntityTypeId']</value>
      <webElementGuid>5beeb567-f361-4d89-bca6-4c8ca33205ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>3fe22264-e0d7-4dac-9e3b-a0cf6ddc229b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/following::select[1]</value>
      <webElementGuid>d46d32a6-9957-48fa-b69c-271475ed4f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a1bf40e7-3ca5-435c-a364-c55c1b7aa430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.compEntityTypeId' and @id = 'onboardDto.compEntityTypeId' and (text() = 'Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA' or . = 'Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA')]</value>
      <webElementGuid>4f58fe2d-8537-4c4b-a6f3-5afa991f6e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
