<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Kelolaan Dana Pertahun Rp100 j_ced9d8</name>
   <tag></tag>
   <elementGuidId>5b29a4be-31a9-4d6a-8db3-5837a2ba0163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='onboardDto.annualFundMgmt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Kelolaan Dana Pertahun*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c4dc7d7-151a-4df7-8d64-2e09deb97a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.annualFundMgmt</value>
      <webElementGuid>6e84522a-190e-4551-a779-08a5fe5b88c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.annualFundMgmt</value>
      <webElementGuid>46d71001-3677-4fb1-85fc-29879a522979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3745eee-f809-4e04-8880-498a47405e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>577837eb-b7c6-4b70-9d4b-5994a3154419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kelolaan Dana Pertahun&lt;= Rp100 jt&lt;= Rp100 jt - Rp300 jt&lt;= Rp300 jt - Rp2.5 M&lt;= Rp50 M - Rp300 M&lt;= Rp300 M - Rp600 M</value>
      <webElementGuid>a74f3cbd-b421-4bd1-a55a-e4f97a54ed0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.annualFundMgmt&quot;)</value>
      <webElementGuid>2fef1fad-74d0-4299-882c-141359a00cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardDto.annualFundMgmt']</value>
      <webElementGuid>395f192b-a33f-4ded-b657-3a0655a315f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div[9]/div/div/select</value>
      <webElementGuid>68759d10-ae9d-4259-92ff-07aaf4bec98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::select[1]</value>
      <webElementGuid>0bb60a08-d3ea-4faf-8f93-b5982a50c191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Pelanggan'])[1]/preceding::select[1]</value>
      <webElementGuid>381fee71-4867-4028-b139-6e5532646dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/select</value>
      <webElementGuid>edd70d59-815c-4bab-8ac1-8c731fc4b763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.annualFundMgmt' and @id = 'onboardDto.annualFundMgmt' and (text() = 'Pilih Kelolaan Dana Pertahun&lt;= Rp100 jt&lt;= Rp100 jt - Rp300 jt&lt;= Rp300 jt - Rp2.5 M&lt;= Rp50 M - Rp300 M&lt;= Rp300 M - Rp600 M' or . = 'Pilih Kelolaan Dana Pertahun&lt;= Rp100 jt&lt;= Rp100 jt - Rp300 jt&lt;= Rp300 jt - Rp2.5 M&lt;= Rp50 M - Rp300 M&lt;= Rp300 M - Rp600 M')]</value>
      <webElementGuid>3b705212-f34d-4d21-a285-c629774cb763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
