<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih ProvinsiKalimantan SelatanKali_d34dfd</name>
   <tag></tag>
   <elementGuidId>bff6e788-68fa-4d60-900c-ae044b18324e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='field-:rj:'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;onboardDto\.provinceId&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8d878d22-b229-4497-98fe-c05ddd41775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.provinceId</value>
      <webElementGuid>ac755eab-cc92-4b8c-b75f-602ee253356f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rj:</value>
      <webElementGuid>959be96c-3c06-4a32-b051-4423e533e9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-l1m0k1</value>
      <webElementGuid>0a70b013-861e-455f-a364-748983f755d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih ProvinsiKalimantan SelatanKalimantan TimurNusa Tenggara TimurNanggroe Aceh DarussalamRiauDKI JakartaKalimantan BaratSulawesi TengahPapuaSumatera UtaraSumatera BaratJawa TimurGorontaloBaliKalimantan TengahSumatera SelatanJawa BaratBantenNusa Tenggara BaratLampungMaluku UtaraSulawesi SelatanPapua BaratBengkuluJawa TengahDI YogyakartaJambiBangka BelitungMalukuKalimantan UtaraKepulauan RiauSulawesi BaratSulawesi UtaraSulawesi Tenggara</value>
      <webElementGuid>e4c7b545-a56f-4fd8-b8e7-7491e1246ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[1]/form[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1vg8b7f&quot;]/div[@class=&quot;css-1l4w6pd&quot;]/div[@class=&quot;css-16djiq0&quot;]/form[1]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-select__wrapper css-15ca0qf&quot;]/select[@id=&quot;field-:rj:&quot;]</value>
      <webElementGuid>49753135-76ee-4018-a530-1944284a9069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='field-:rj:'])[2]</value>
      <webElementGuid>a5ef9abd-9f0a-4aaf-aa67-a650b8d480ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[2]/div[3]/div/div/select</value>
      <webElementGuid>1b118aee-07da-4d32-9bdb-14195b68f7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>8b037615-e479-4574-9389-be1045ccfb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi harus dipilih'])[1]/preceding::select[1]</value>
      <webElementGuid>66f1f1d0-2561-4c45-9fb9-dad462e11e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>b5513075-c753-4ba0-89a1-028f9e2fbe38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.provinceId' and @id = 'field-:rj:' and (text() = 'Pilih ProvinsiKalimantan SelatanKalimantan TimurNusa Tenggara TimurNanggroe Aceh DarussalamRiauDKI JakartaKalimantan BaratSulawesi TengahPapuaSumatera UtaraSumatera BaratJawa TimurGorontaloBaliKalimantan TengahSumatera SelatanJawa BaratBantenNusa Tenggara BaratLampungMaluku UtaraSulawesi SelatanPapua BaratBengkuluJawa TengahDI YogyakartaJambiBangka BelitungMalukuKalimantan UtaraKepulauan RiauSulawesi BaratSulawesi UtaraSulawesi Tenggara' or . = 'Pilih ProvinsiKalimantan SelatanKalimantan TimurNusa Tenggara TimurNanggroe Aceh DarussalamRiauDKI JakartaKalimantan BaratSulawesi TengahPapuaSumatera UtaraSumatera BaratJawa TimurGorontaloBaliKalimantan TengahSumatera SelatanJawa BaratBantenNusa Tenggara BaratLampungMaluku UtaraSulawesi SelatanPapua BaratBengkuluJawa TengahDI YogyakartaJambiBangka BelitungMalukuKalimantan UtaraKepulauan RiauSulawesi BaratSulawesi UtaraSulawesi Tenggara')]</value>
      <webElementGuid>c82f0256-ecb6-414a-ad81-f784b53ad2b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
