<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_JL KECAMATA</name>
   <tag></tag>
   <elementGuidId>985f2a79-1f69-42ae-878d-7346cb5d3f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='onboardDto.compAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Alamat Lengkap&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7d83f685-2a22-446c-a16c-414f7116c864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>e8e18aeb-1787-4026-8c74-63693dcaa2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Lengkap</value>
      <webElementGuid>c8aa009a-afce-48bf-a23b-6fe3af18c65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compAddress</value>
      <webElementGuid>8d089e17-4913-40c6-85f7-7eb7143671de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>83942c02-707f-47d7-87ad-7b8d11604112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-textarea w-full bg-white border border-gray-300 hover:border-[#FF6B00] px-4 py-2 text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-31809p</value>
      <webElementGuid>ded624c7-3cb7-463e-9d29-757f8dda833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JL KECAMATA</value>
      <webElementGuid>bfbe22c5-873d-4c0c-b4d4-7f697115c7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.compAddress&quot;)</value>
      <webElementGuid>2bb21270-c01f-4fef-8aa1-b832c827ff5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='onboardDto.compAddress']</value>
      <webElementGuid>a1074415-d166-4b86-8bba-b45564d9329c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/form/div/div[4]/textarea</value>
      <webElementGuid>67a7ab93-ca11-4812-b609-96f8b6ac646d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Email Perusahaan'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b479d81c-f852-4968-b3c5-cac02bc47797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JL KECAMATA']/parent::*</value>
      <webElementGuid>6890c4ce-b4c0-469e-878d-c556437faa9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>58b170cc-2c02-4930-abbc-14e55206acec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'onboardDto.compAddress' and @placeholder = 'Masukkan Alamat Lengkap' and @id = 'onboardDto.compAddress' and (text() = 'JL KECAMATA' or . = 'JL KECAMATA')]</value>
      <webElementGuid>30291aca-75d5-4795-9bb2-4bff70f670dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
