<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Bentuk Badan UsahaPTBankKopera_6d3d37</name>
   <tag></tag>
   <elementGuidId>78233dd8-01d6-4e5c-b500-f3b744cf2b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='onboardDto.compEntityTypeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bentuk Badan Usaha*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fa40f0c5-c7ef-4316-b16a-8bf4e96c5e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onboardDto.compEntityTypeId</value>
      <webElementGuid>b4258ef4-1f3a-4109-8cd0-e705476cb509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onboardDto.compEntityTypeId</value>
      <webElementGuid>8907da2f-a9e8-47dd-a497-f1a93a238d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>83866c5e-d235-4921-8c85-2f6be17807e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select w-full bg-white border border-[#D0D5DD] hover:border-[#FF6B00] text-black rounded-lg focus:outline focus:outline-4 focus:outline-outlineColorBrand css-swqbh5</value>
      <webElementGuid>307fa69a-5e88-48ab-be9b-f9fb4edde02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA</value>
      <webElementGuid>06fa2068-9340-40d0-bff0-b37f24dd5bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onboardDto.compEntityTypeId&quot;)</value>
      <webElementGuid>f2732421-7173-4eed-842b-0bf1eda11671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='onboardDto.compEntityTypeId']</value>
      <webElementGuid>ea1389a9-2c80-49be-9a94-aea79e15b299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div/div[2]/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>447899fd-ebf9-455c-8215-970b2aaf25d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/following::select[1]</value>
      <webElementGuid>39ffc16f-8350-4182-a742-54f0fc9a85f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>00c79010-5668-4a82-8786-2b6c658f6def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'onboardDto.compEntityTypeId' and @id = 'onboardDto.compEntityTypeId' and (text() = 'Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA' or . = 'Pilih Bentuk Badan UsahaPTBankKoperasiBUMNPMAYayasanBUMDInstansi PemerintahKantor PerwakilanCVFA')]</value>
      <webElementGuid>199cbce0-1e24-4925-af6e-b69dd270c224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
