<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_pilih_cabang_pengajuan</name>
   <tag></tag>
   <elementGuidId>de57668b-f33b-4a87-955d-6d86337ea0ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[2]/div/form/div/div[2]/div[2]/div/div[2]/div/div/div/div[1]/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@role = 'combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f47ebdda-775a-4428-b5e4-f5e2ef013d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>547fe93b-53de-4641-95fc-62321b48aede</webElementGuid>
   </webElementProperties>
</WebElementEntity>
