<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ProvinsiPilih ProvinsiBALIBANGKA BELITU_c57055</name>
   <tag></tag>
   <elementGuidId>c677fa5b-497d-4c5e-b32c-c28c217d25bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=group >> div >> internal:has-text=&quot;Provinsi*Pilih ProvinsiBALIBANGKA BELITUNGBANTENBENGKULUDAERAH ISTIMEWA YOGYAKAR&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>526ed49c-21e8-47c0-8824-498aa880ef5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-j7qwjs</value>
      <webElementGuid>e52e1bbd-9b8c-4980-bbee-25eaeba88cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Provinsi*Pilih ProvinsiBALIBANGKA BELITUNGBANTENBENGKULUDAERAH ISTIMEWA YOGYAKARTADKI JAKARTAGORONTALOHONGKONGJAMBIJAWA BARATJAWA TENGAHJAWA TIMURKALIMANTAN BARATKALIMANTAN SELATANKALIMANTAN TENGAHKALIMANTAN TIMURKALIMANTAN UTARAKEPULAUAN RIAULAMPUNGMALUKUMALUKU TENGAHMALUKU TENGGARA BARATMALUKU UTARANANGGROE ACEH DARUSSALAMNUSA TENGGARA BARATNUSA TENGGARA TIMURPAPUAPAPUA BARATRIAUSINGAPURASULAWESI BARATSULAWESI SELATANSULAWESI TENGAHSULAWESI TENGGARASULAWESI UTARASUMATERA BARATSUMATERA SELATANSUMATERA UTARAPAPUA BARAT RAYAPAPUA SELATANPAPUA TENGAHKota*Pilih Kabupaten/KotaWIL. KOTA JAKARTA SELATANKAB. KARAWANGKAB. BEKASIKAB. KEP. SERIBUWIL. KOTA JAKARTA BARATWIL. KOTA JAKARTA PUSATWIL. KOTA JAKARTA SELATANWIL. KOTA JAKARTA TIMURWIL. KOTA JAKARTA PUSAT</value>
      <webElementGuid>ecc6144f-b580-498e-958d-fe855e2a51b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]/div[@class=&quot;css-11b5mf8&quot;]/div[@class=&quot;css-u6v8er&quot;]/div[@class=&quot;css-16djiq0&quot;]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-j7qwjs&quot;]</value>
      <webElementGuid>d6491e69-3734-46c1-8af6-bb3e323a94ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[3]</value>
      <webElementGuid>9394486d-4b0a-48e7-bdc6-6893a828b935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[4]</value>
      <webElementGuid>ed5459f1-e41d-43c8-85aa-370c8533807e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>c2188666-9475-4104-ac86-8872cb2e8f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Provinsi*Pilih ProvinsiBALIBANGKA BELITUNGBANTENBENGKULUDAERAH ISTIMEWA YOGYAKARTADKI JAKARTAGORONTALOHONGKONGJAMBIJAWA BARATJAWA TENGAHJAWA TIMURKALIMANTAN BARATKALIMANTAN SELATANKALIMANTAN TENGAHKALIMANTAN TIMURKALIMANTAN UTARAKEPULAUAN RIAULAMPUNGMALUKUMALUKU TENGAHMALUKU TENGGARA BARATMALUKU UTARANANGGROE ACEH DARUSSALAMNUSA TENGGARA BARATNUSA TENGGARA TIMURPAPUAPAPUA BARATRIAUSINGAPURASULAWESI BARATSULAWESI SELATANSULAWESI TENGAHSULAWESI TENGGARASULAWESI UTARASUMATERA BARATSUMATERA SELATANSUMATERA UTARAPAPUA BARAT RAYAPAPUA SELATANPAPUA TENGAHKota*Pilih Kabupaten/KotaWIL. KOTA JAKARTA SELATANKAB. KARAWANGKAB. BEKASIKAB. KEP. SERIBUWIL. KOTA JAKARTA BARATWIL. KOTA JAKARTA PUSATWIL. KOTA JAKARTA SELATANWIL. KOTA JAKARTA TIMURWIL. KOTA JAKARTA PUSAT' or . = 'Provinsi*Pilih ProvinsiBALIBANGKA BELITUNGBANTENBENGKULUDAERAH ISTIMEWA YOGYAKARTADKI JAKARTAGORONTALOHONGKONGJAMBIJAWA BARATJAWA TENGAHJAWA TIMURKALIMANTAN BARATKALIMANTAN SELATANKALIMANTAN TENGAHKALIMANTAN TIMURKALIMANTAN UTARAKEPULAUAN RIAULAMPUNGMALUKUMALUKU TENGAHMALUKU TENGGARA BARATMALUKU UTARANANGGROE ACEH DARUSSALAMNUSA TENGGARA BARATNUSA TENGGARA TIMURPAPUAPAPUA BARATRIAUSINGAPURASULAWESI BARATSULAWESI SELATANSULAWESI TENGAHSULAWESI TENGGARASULAWESI UTARASUMATERA BARATSUMATERA SELATANSUMATERA UTARAPAPUA BARAT RAYAPAPUA SELATANPAPUA TENGAHKota*Pilih Kabupaten/KotaWIL. KOTA JAKARTA SELATANKAB. KARAWANGKAB. BEKASIKAB. KEP. SERIBUWIL. KOTA JAKARTA BARATWIL. KOTA JAKARTA PUSATWIL. KOTA JAKARTA SELATANWIL. KOTA JAKARTA TIMURWIL. KOTA JAKARTA PUSAT')]</value>
      <webElementGuid>2e64f3ab-d740-4890-8872-c1635bac65ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
