<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Akte  PerijinanNPWPNPWP harus 16 digitT_ddb055</name>
   <tag></tag>
   <elementGuidId>a0801f66-e17b-433f-b45b-85414116267f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-q2icr7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-q2icr7</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a2a5ded-1df3-4020-804b-b6a5404aa26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-q2icr7</value>
      <webElementGuid>d67b4b56-761c-45cc-9084-78766606e8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akte &amp; PerijinanNPWP*NPWP harus 16 digitTempat Dikeluarkan IdentitasNomor Akte Pengesahan*Tanggal Pengesahan*Nomor Akte Pendirian/Anggaran Dasar*Tanggal Pendirian*Nama Notaris*Tempat Akte Dibuat*Nomor Akte PerubahanTanggal PerubahanNotarisNomor Izin Usaha / NIB*Tanggal Pembuatan*Tanggal ExpiredSelanjutnya</value>
      <webElementGuid>0c0feac1-e4c1-42db-a267-bece3e4053d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]</value>
      <webElementGuid>1b895650-55fc-4f7a-b34f-c89d7bbb4a0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div</value>
      <webElementGuid>e2f7f39e-7809-4734-ae80-20c0f0342b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::div[1]</value>
      <webElementGuid>4341dc1c-eef2-4a83-9c01-022d3319ad86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pernyataan &amp; Syarat Ketentuan'])[1]/following::div[4]</value>
      <webElementGuid>5dc940ad-3ecc-4431-8d41-ab71f9cb468a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div</value>
      <webElementGuid>38e2b4b5-7068-43dd-a83e-201d0a9cb7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Akte &amp; PerijinanNPWP*NPWP harus 16 digitTempat Dikeluarkan IdentitasNomor Akte Pengesahan*Tanggal Pengesahan*Nomor Akte Pendirian/Anggaran Dasar*Tanggal Pendirian*Nama Notaris*Tempat Akte Dibuat*Nomor Akte PerubahanTanggal PerubahanNotarisNomor Izin Usaha / NIB*Tanggal Pembuatan*Tanggal ExpiredSelanjutnya' or . = 'Akte &amp; PerijinanNPWP*NPWP harus 16 digitTempat Dikeluarkan IdentitasNomor Akte Pengesahan*Tanggal Pengesahan*Nomor Akte Pendirian/Anggaran Dasar*Tanggal Pendirian*Nama Notaris*Tempat Akte Dibuat*Nomor Akte PerubahanTanggal PerubahanNotarisNomor Izin Usaha / NIB*Tanggal Pembuatan*Tanggal ExpiredSelanjutnya')]</value>
      <webElementGuid>e47c4813-811e-47ae-9e97-b838a310e961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
