<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - ttd</name>
   <tag></tag>
   <elementGuidId>7eee71b1-a2b7-423f-aafe-a6fa07714cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='upload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;upload&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.css-mwpxdx > img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>418f6b77-74b1-42f0-ba88-ebd7c7d86da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../assets/images/upload.png</value>
      <webElementGuid>13f0889b-1bc2-4750-8fd8-0f2ae95a28cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>a0ab16a8-ea2f-4563-b4d3-d1cf65c6a1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]/div[@class=&quot;css-11b5mf8&quot;]/div[@class=&quot;css-u6v8er&quot;]/div[@class=&quot;css-1qkj5u4&quot;]/label[2]/div[@class=&quot;css-1ep4wpn&quot;]/div[@class=&quot;css-gmuwbf&quot;]/div[@class=&quot;css-mwpxdx&quot;]/img[1]</value>
      <webElementGuid>d7bc3fea-d990-4e9b-8a42-78c14ba32886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/label[2]/div/div/div/img</value>
      <webElementGuid>37cbbeaa-f3fd-4788-97dc-de03b934ce03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='upload']</value>
      <webElementGuid>afbd1cae-fad2-47ca-8da3-01725e21b829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>b7c01ec2-18ca-4510-8d68-283882292e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../assets/images/upload.png' and @alt = 'upload']</value>
      <webElementGuid>f1d3d037-e255-4773-ae28-1205e935346d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
