<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__namaPejabat</name>
   <tag></tag>
   <elementGuidId>d35473d4-e899-4c01-b529-1efc1e074ec7</elementGuidId>
   <imagePath>Screenshots/Targets/Page_BNIDirect/input__namaPejabat.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'namaPejabat' and @placeholder = 'Masukkan nama lengkap sesuai identitas' and @id = 'field-:rb:']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_BNIDirect/input__namaPejabat.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan nama lengkap sesuai identitas&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d410dca4-8dae-4220-bd51-e059c818a395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55ee90c4-541d-45b8-82d4-a6ebdceb259e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>namaPejabat</value>
      <webElementGuid>d025c4e4-6d3f-493b-a4dd-7490ea48114d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama lengkap sesuai identitas</value>
      <webElementGuid>49ceefd4-cf9b-45ff-94fc-612443f8301d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rb:</value>
      <webElementGuid>cbe81529-4d68-4c86-b728-2bdf22d48427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-10ex9a1</value>
      <webElementGuid>23968f05-b611-4dd9-baae-92cc2f291e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]/div[@class=&quot;css-11b5mf8&quot;]/div[@class=&quot;css-u6v8er&quot;]/div[@class=&quot;css-cakzji&quot;]/form[1]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-1pf2w37&quot;]/form[1]/div[1]/input[@id=&quot;field-:rb:&quot;]</value>
      <webElementGuid>d10929c4-bfbf-45ac-893c-2f1ec48ca1f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-:rb:']</value>
      <webElementGuid>4f1fa3bd-97c5-4b53-8af7-a7dea4a34572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/form/div/div[2]/form/div/input</value>
      <webElementGuid>e7be08f5-b882-470a-b6d0-621c8e8e260b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3e411d29-de25-4eea-a28d-9c8225356f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'namaPejabat' and @placeholder = 'Masukkan nama lengkap sesuai identitas' and @id = 'field-:rb:']</value>
      <webElementGuid>fa7395ed-3f89-4064-a2d4-dc0f9c97f6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
