<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tujuan_Investasi</name>
   <tag></tag>
   <elementGuidId>5375c4e1-2d45-4590-89d3-37b2cdb3fb8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[@value = 'Investasi' and (text() = 'Investasi' or . = 'Investasi')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[2]/div[3]/div/div[1]/div/select/option[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d5dbeb21-88d1-4274-b49d-2e63afabbe53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Investasi</value>
      <webElementGuid>1f6fb47d-f0f6-4e24-8eae-ed2b5225f8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investasi</value>
      <webElementGuid>67a77802-430d-4e65-97bb-37e0d57e1f5e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
