<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KecamatanKEC. CENGKARENGKEC. G_064785</name>
   <tag></tag>
   <elementGuidId>78a508a2-3dee-4c2a-9563-d7b43b5c5779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='field-:rg:'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f2bc87c5-1aef-4323-8ac1-3e1cefb40799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rg:</value>
      <webElementGuid>c32c56ac-2667-4ab5-9e3f-5e0622c09f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-1jtun3o</value>
      <webElementGuid>d986b6bd-47b3-48a6-8e5e-dce652715509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KecamatanKEC. CENGKARENGKEC. GROGOL PETAMBURANKEC. KEBON JERUKKEC. KEMBANGANKEC. PALMERAHCENGKARENGGAMBIRGROGOL PETAMBURANINACTIVEKALIDERESKEBON JERUKKEMBANGANPADEMANGANPALMERAHPENJARINGANTAMAN SARITAMBORACIPAYUNGKEMAYORANKOTA JAKARTA BARATLARANGANMAMPANG PRAPATANPANCORANSAWAH BESARSETIABUDITAMANSARIKALI DERESCENGKARENG TIMURCENGKARENG BARATTEGAL ALURDURI KOSAMBIKEDOYA SELATANKEDOYA UTARA</value>
      <webElementGuid>ec07a2d3-632e-4f52-aa62-827e1528404c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]/div[@class=&quot;css-11b5mf8&quot;]/div[@class=&quot;css-u6v8er&quot;]/div[@class=&quot;css-16djiq0&quot;]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-select__wrapper css-1i263w5&quot;]/select[@id=&quot;field-:rg:&quot;]</value>
      <webElementGuid>d6d6248a-56cd-4f8e-a05c-6154b85716c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='field-:rg:'])[4]</value>
      <webElementGuid>6ab88334-af0c-4fec-95e4-e44a581d808c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[5]/div/select</value>
      <webElementGuid>290cecc1-468c-4348-9818-88150f632a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>23d28089-cfb3-488f-a040-85f9f90de0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>e6826309-9d7b-4df5-9812-7e4fcadd141e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>73ce794b-a4a2-4d02-b38c-ee12801d3cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'field-:rg:' and (text() = 'Pilih KecamatanKEC. CENGKARENGKEC. GROGOL PETAMBURANKEC. KEBON JERUKKEC. KEMBANGANKEC. PALMERAHCENGKARENGGAMBIRGROGOL PETAMBURANINACTIVEKALIDERESKEBON JERUKKEMBANGANPADEMANGANPALMERAHPENJARINGANTAMAN SARITAMBORACIPAYUNGKEMAYORANKOTA JAKARTA BARATLARANGANMAMPANG PRAPATANPANCORANSAWAH BESARSETIABUDITAMANSARIKALI DERESCENGKARENG TIMURCENGKARENG BARATTEGAL ALURDURI KOSAMBIKEDOYA SELATANKEDOYA UTARA' or . = 'Pilih KecamatanKEC. CENGKARENGKEC. GROGOL PETAMBURANKEC. KEBON JERUKKEC. KEMBANGANKEC. PALMERAHCENGKARENGGAMBIRGROGOL PETAMBURANINACTIVEKALIDERESKEBON JERUKKEMBANGANPADEMANGANPALMERAHPENJARINGANTAMAN SARITAMBORACIPAYUNGKEMAYORANKOTA JAKARTA BARATLARANGANMAMPANG PRAPATANPANCORANSAWAH BESARSETIABUDITAMANSARIKALI DERESCENGKARENG TIMURCENGKARENG BARATTEGAL ALURDURI KOSAMBIKEDOYA SELATANKEDOYA UTARA')]</value>
      <webElementGuid>a1f3c494-1f5a-4af5-beab-16e9efc453e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
