<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KelurahanJATI PULOKEMANGGISANK_5cca53</name>
   <tag></tag>
   <elementGuidId>6c9302a4-bda1-4e7a-af1a-ace6a151e6de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='field-:rg:'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Pilih KelurahanJATI PULOKEMANGGISANKOTA BAMBUPALMERAH$/ >> internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8922e381-71f8-4dc2-98df-0a59bcbb9bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rg:</value>
      <webElementGuid>0ba2c3c9-4693-4e51-b482-b664b6cbcb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-1jtun3o</value>
      <webElementGuid>0578a17e-574a-4c47-bd18-8286c12cadd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KelurahanJATI PULOKEMANGGISANKOTA BAMBUPALMERAH</value>
      <webElementGuid>b6394645-1895-4c4c-957c-bb0b11b54a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-1evpsxe&quot;]/div[@class=&quot;css-n6ujqp&quot;]/div[@class=&quot;css-q2icr7&quot;]/div[@class=&quot;css-11b5mf8&quot;]/div[@class=&quot;css-u6v8er&quot;]/div[@class=&quot;css-16djiq0&quot;]/div[@class=&quot;chakra-form-control css-1co3er0&quot;]/div[@class=&quot;css-0&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;chakra-select__wrapper css-1i263w5&quot;]/select[@id=&quot;field-:rg:&quot;]</value>
      <webElementGuid>03b5013f-23dd-4b51-9196-ea922acc126d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='field-:rg:'])[5]</value>
      <webElementGuid>1059d078-a515-4c6b-a3fa-39a69a4bddb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[7]/div/select</value>
      <webElementGuid>8970848e-2417-4d01-89cd-3f3f73ce70b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>a52a1d81-a735-46f1-ae9f-badaf96bfcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>efe94480-19d7-4ce1-9ae0-c3085e57e77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>5f1e5944-3d15-4794-9312-400c90f03489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'field-:rg:' and (text() = 'Pilih KelurahanJATI PULOKEMANGGISANKOTA BAMBUPALMERAH' or . = 'Pilih KelurahanJATI PULOKEMANGGISANKOTA BAMBUPALMERAH')]</value>
      <webElementGuid>a0587e16-821b-4925-a59e-659201995a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
